import { ContentCategory } from "./types";
import { referenceItems } from "./referenceData";

export const subGenreByGenre: Record<string, string[]> = {
  "Hip-Hop": [
    "Boom Bap",
    "Trap",
    "Drill",
    "Cloud Rap",
    "Conscious Hip-Hop",
    "Horrorcore",
    "Jazz Rap",
    "Gangsta Rap",
    "G-Funk",
    "Alternative Hip-Hop",
    "Nerdcore",
    "Crunk",
    "Memphis Rap",
    "Lo-Fi Hip-Hop",
    "Mumble Rap",
    "Experimental Hip-Hop",
    "Chopped and Screwed",
    "Industrial Hip-Hop",
    "Abstract Hip-Hop",
    "Political Hip-Hop",
    "East Coast Hip-Hop",
    "West Coast Hip-Hop",
    "Southern Hip-Hop",
    "Bounce",
    "Hyphy",
    "Trap Metal",
    "Rage Rap",
    "Emo Rap",
    "Christian Hip-Hop",
    "Latin Trap",
    "UK Drill",
    "Freestyle Rap",
    "Party Rap",
    "Hardcore Hip-Hop",
    "Jazz Trap",
    "Old School Hip-Hop",
    "Underground Hip-Hop",
    "Comedy Rap",
    "Rap Rock",
    "Rapcore",
    "Mafioso Rap",
    "Snap Music",
    "Turntablism",
    "Alternative Trap",
    "Phonk",
    "Plugg",
    "Pluggnb",
    "Detroit Rap",
    "Jersey Club Rap",
    "Miami Bass Rap",
  ],
  Rap: [
    "Boom Bap",
    "Trap",
    "Drill",
    "Cloud Rap",
    "Conscious Hip-Hop",
    "Horrorcore",
    "Jazz Rap",
    "Gangsta Rap",
    "G-Funk",
    "Alternative Hip-Hop",
    "Nerdcore",
    "Crunk",
    "Memphis Rap",
    "Lo-Fi Hip-Hop",
    "Mumble Rap",
    "Experimental Hip-Hop",
    "Chopped and Screwed",
    "Industrial Hip-Hop",
    "Abstract Hip-Hop",
    "Political Hip-Hop",
    "East Coast Hip-Hop",
    "West Coast Hip-Hop",
    "Southern Hip-Hop",
    "Bounce",
    "Hyphy",
    "Trap Metal",
    "Rage Rap",
    "Emo Rap",
    "Christian Hip-Hop",
    "Latin Trap",
    "UK Drill",
    "Freestyle Rap",
    "Party Rap",
    "Hardcore Hip-Hop",
    "Jazz Trap",
    "Old School Hip-Hop",
    "Underground Hip-Hop",
    "Comedy Rap",
    "Rap Rock",
    "Rapcore",
    "Mafioso Rap",
    "Snap Music",
    "Turntablism",
    "Alternative Trap",
    "Phonk",
    "Plugg",
    "Pluggnb",
    "Detroit Rap",
    "Jersey Club Rap",
    "Miami Bass Rap",
  ],
  Pop: [
    "Synthpop",
    "Electropop",
    "Indie Pop",
    "Dance Pop",
    "Dream Pop",
    "Bubblegum Pop",
    "Art Pop",
    "Hyperpop",
    "Chamber Pop",
    "Baroque Pop",
    "Power Pop",
    "Sunshine Pop",
    "Teen Pop",
    "K-Pop",
    "J-Pop",
    "Sophisti-Pop",
    "Ambient Pop",
    "Pop Rock",
    "Bedroom Pop",
    "Experimental Pop",
    "Dark Pop",
    "Tropical Pop",
    "Electroclash Pop",
    "Disco Pop",
    "Folk Pop",
    "Orchestral Pop",
    "Soft Pop",
    "Indie Electropop",
    "Noise Pop",
    "Glam Pop",
    "Art-Pop Ballad",
    "Neo-Pop",
    "Psychedelic Pop",
    "Britpop",
    "Sunshine Indie Pop",
    "Acoustic Pop",
    "Latin Pop",
    "Adult Contemporary Pop",
    "Minimal Pop",
    "Cinematic Pop",
  ],
  Country: [
    "Country Pop",
    "Outlaw Country",
    "Bluegrass",
    "Country Rock",
    "Honky Tonk",
    "Western Swing",
    "Americana",
    "Alt-Country",
    "Bro-Country",
    "Texas Country",
    "Country Gospel",
    "Neotraditional Country",
    "Nashville Sound",
    "Bakersfield Sound",
    "Progressive Bluegrass",
    "Red Dirt",
    "Appalachian Country",
    "Western Ballad",
    "Cowpunk",
    "Cajun Country",
    "Country Soul",
    "Traditional Country",
    "Contemporary Country",
    "Bluegrass Gospel",
    "Country Blues",
    "Hillbilly Boogie",
    "Countrypolitan",
    "Roots Country",
    "Folk Country",
    "Americana Folkgrass",
  ],
  Rock: [
    "Hard Rock",
    "Classic Rock",
    "Punk Rock",
    "Post-Punk",
    "Garage Rock",
    "Glam Rock",
    "Progressive Rock",
    "Psychedelic Rock",
    "Surf Rock",
    "Stoner Rock",
    "Southern Rock",
    "Space Rock",
    "Math Rock",
    "Noise Rock",
    "Art Rock",
    "Folk Rock",
    "Indie Rock",
    "Blues Rock",
    "Shoegaze Rock",
    "Post-Rock",
    "Gothic Rock",
    "Grunge",
    "Arena Rock",
    "Industrial Rock",
    "Acid Rock",
    "Soft Rock",
    "Alternative Rock",
    "Symphonic Rock",
    "Proto-Punk",
    "Cowpunk Rock",
    "Desert Rock",
    "Swamp Rock",
    "Heartland Rock",
    "Garage Punk",
    "Jangle Rock",
    "Sludge Rock",
    "Brit Rock",
    "Dream Rock",
    "Heavy Psych Rock",
    "Gothic Punk",
    "College Rock",
    "Krautrock",
    "Melodic Rock",
    "Rap Metal Rock",
    "Funk Rock",
    "Dance-Rock",
    "Experimental Rock",
    "Garage Revival",
    "Neo-Psychedelia",
    "Mod Revival",
    "Lo-Fi Rock",
    "Blackgaze Rock",
    "Space Psychedelia",
    "Riot Grrrl",
    "Skate Punk Rock",
    "Proto-Metal Rock",
    "New Wave Rock",
    "No Wave",
    "Psych Garage",
    "Dreamgaze Rock",
  ],
  "R&B": [
    "Contemporary R&B",
    "Alternative R&B",
    "New Jack Swing",
    "Quiet Storm",
    "Neo-R&B",
    "Electro-R&B",
    "Funkstep R&B",
    "Urban Contemporary",
    "Pop R&B",
    "Trap R&B",
    "Bedroom R&B",
    "Atmospheric R&B",
    "Indie R&B",
    "Ambient R&B",
    "Dark R&B",
    "Experimental R&B",
    "Neo-Soul R&B",
    "Gospel R&B",
    "Smooth R&B",
    "Dancehall R&B",
    "Acoustic R&B",
    "Electronic R&B",
    "Minimal R&B",
    "Downtempo R&B",
    "Jazz R&B",
    "Soulful R&B",
    "Afrofusion R&B",
    "Alternative Soul R&B",
    "Modern R&B Ballad",
    "Club R&B",
    "Slow Jam R&B",
    "Retro R&B",
    "Synth R&B",
    "Dreamy R&B",
    "Lo-Fi R&B",
  ],
  Soul: [
    "Neo Soul",
    "Southern Soul",
    "Philly Soul",
    "Deep Soul",
    "Blue-Eyed Soul",
    "Psychedelic Soul",
    "Progressive Soul",
    "Smooth Soul",
    "Soul Jazz",
    "Gospel Soul",
    "Funk Soul",
    "Northern Soul",
    "Chicago Soul",
    "Memphis Soul",
    "Motown Soul",
    "Retro Soul",
    "Swamp Soul",
    "Country Soul",
    "Latin Soul",
    "Electric Soul",
    "Orchestral Soul",
    "Soul Blues",
    "Crossover Soul",
    "Classic Soul",
    "Contemporary Soul",
  ],
  Latin: [
    "Reggaeton",
    "Salsa",
    "Bachata",
    "Merengue",
    "Cumbia",
    "Bossa Nova",
    "Samba",
    "Norteño",
    "Mariachi",
    "Latin Jazz",
    "Regional Mexican",
    "Dembow",
    "Latin Rock",
    "Latin Alternative",
    "Tejano",
    "Corrido",
    "Banda",
    "Ranchera",
    "Bolero",
    "Son Cubano",
    "Timba",
    "Vallenato",
    "Latin Funk",
    "Latin House",
    "Flamenco Pop",
    "Nueva Canción",
    "Tropical Latin",
    "Salsa Dura",
    "Romántica Latina",
    "Urbano Latino",
    "Mambo",
    "Cha-Cha-Cha",
    "Latin Ballad",
    "Afro-Cuban",
    "Cumbia Sonidera",
  ],
  Electronic: [
    "House",
    "Deep House",
    "Tech House",
    "Progressive House",
    "Electro House",
    "Future House",
    "Bass House",
    "Tropical House",
    "Afro House",
    "Organic House",
    "Techno",
    "Minimal Techno",
    "Detroit Techno",
    "Acid Techno",
    "Melodic Techno",
    "Industrial Techno",
    "Trance",
    "Psytrance",
    "Uplifting Trance",
    "Goa Trance",
    "Progressive Trance",
    "Hard Trance",
    "Ambient",
    "Dark Ambient",
    "Space Ambient",
    "Drone",
    "Chillout",
    "Downtempo",
    "IDM",
    "Glitch",
    "Glitch Hop",
    "Breakbeat",
    "Big Beat",
    "Nu Skool Breaks",
    "Drum & Bass",
    "Liquid Drum & Bass",
    "Neurofunk",
    "Jump-Up",
    "Jungle",
    "Dubstep",
    "Brostep",
    "Riddim",
    "Chillstep",
    "Future Bass",
    "Wave",
    "Hardstyle",
    "Hardcore",
    "Gabber",
    "Happy Hardcore",
    "Frenchcore",
    "UK Garage",
    "Speed Garage",
    "2-Step Garage",
    "Electro",
    "Electroswing",
    "Electroclash",
    "Synthwave",
    "Vaporwave",
    "Chillwave",
    "Retrowave",
    "Witch House",
    "Darkwave Electronic",
    "EBM",
    "Microhouse",
    "Moombahton",
    "Baile Funk Electronic",
    "Footwork",
    "Juke",
    "Plunderphonics",
    "Lo-Fi Electronic",
  ],
  Alternative: [
    "Indie Alternative",
    "Dream Alternative",
    "Dark Alternative",
    "Experimental Alternative",
    "Post-Alternative",
    "Alternative Metal",
    "Alternative Punk",
    "Alternative Dance",
    "Alternative Pop",
    "Alternative Folk",
    "Alternative Country",
    "Alternative Electronic",
    "Alternative Wave",
    "Alternative Emo",
    "Alternative Grunge",
    "Alternative Noise",
    "Alternative Psychedelia",
    "Alternative Gothic",
    "Alternative Shoegaze",
    "Alternative Singer-Songwriter",
    "Alternative Blues",
    "Alternative Americana",
    "Alternative Chamber Pop",
    "Alternative Art Rock",
    "Alternative Garage",
  ],
  Folk: [
    "Traditional Folk",
    "Contemporary Folk",
    "Indie Folk",
    "Celtic Folk",
    "Folk Punk",
    "Folk Pop",
    "Appalachian Folk",
    "Nordic Folk",
    "Progressive Folk",
    "Psychedelic Folk",
    "Chamber Folk",
    "Anti-Folk",
    "Freak Folk",
    "Roots Folk",
    "Medieval Folk",
    "Mountain Folk",
    "Acoustic Folk",
    "Urban Folk",
    "Folk Revival",
    "Singer-Songwriter Folk",
    "Desert Folk",
    "Ethereal Folk",
    "Balkan Folk",
    "Americana Folk",
    "Storytelling Folk",
  ],
  Jazz: [
    "Bebop",
    "Hard Bop",
    "Cool Jazz",
    "Modal Jazz",
    "Free Jazz",
    "Smooth Jazz",
    "Gypsy Jazz",
    "Jazz Fusion",
    "Acid Jazz",
    "Swing",
    "Big Band Jazz",
    "Dixieland",
    "Avant-Garde Jazz",
    "Third Stream",
    "Post-Bop",
    "Soul Jazz",
    "Latin Jazz Fusion",
    "Jazz-Funk",
    "Nu Jazz",
    "Ethio-Jazz",
    "Spiritual Jazz",
    "Chamber Jazz",
    "Contemporary Jazz",
    "Vocal Jazz",
    "Ragtime Jazz",
    "Stride",
    "Crossover Jazz",
    "Samba Jazz",
    "Bossa Jazz",
    "West Coast Jazz",
    "M-Base",
    "Straight-Ahead Jazz",
    "Experimental Big Band",
    "Piano Jazz",
    "Trumpet Jazz",
  ],
  Classical: [
    "Baroque",
    "Renaissance Classical",
    "Romantic Classical",
    "Modern Classical",
    "Minimalist Classical",
    "Chamber Music",
    "Opera",
    "Choral Classical",
    "Symphony",
    "Concerto",
    "Solo Piano Classical",
    "String Quartet",
    "Impressionist Classical",
    "Neoclassical",
    "Sacred Classical",
    "Avant-Garde Classical",
    "Contemporary Chamber",
    "Oratorio",
    "Cantata",
    "Lied",
    "Art Song",
    "Sonatina",
    "Program Music",
    "Serialism",
    "Electroacoustic Classical",
  ],
  Cinematic: [
    "Film Score",
    "Epic Orchestral",
    "Trailer Music",
    "Hybrid Orchestral",
    "Dark Cinematic",
    "Ambient Cinematic",
    "Adventure Score",
    "Suspense Score",
    "Horror Score",
    "Fantasy Score",
    "Sci-Fi Score",
    "Emotional Score",
    "Documentary Score",
    "Minimal Cinematic",
    "Orchestral Underscore",
    "Heroic Score",
    "Tension Music",
    "Action Score",
    "Piano Cinematic",
    "Post-Classical Cinematic",
  ],
  Gospel: [
    "Traditional Gospel",
    "Contemporary Gospel",
    "Urban Gospel",
    "Southern Gospel",
    "Black Gospel",
    "Gospel Blues",
    "Gospel Choir",
    "Praise and Worship",
    "Quartet Gospel",
    "Country Gospel",
    "Gospel Jazz",
    "Gospel Funk",
    "Gospel Pop",
    "Gospel R&B",
    "Inspirational Gospel",
    "Worship Ballad",
    "Pentecostal Gospel",
    "Hymn Gospel",
    "Revival Gospel",
    "Acoustic Gospel",
    "Choral Gospel",
    "Modern Worship",
    "Congregational Gospel",
    "Gospel Rap",
    "Gospel Soul",
  ],
};

export const initialCategories: ContentCategory[] = [
  {
    key: "genre",
    label: "Genre",
    enabled: true,
    items: [
      "Alternative",
      "Cinematic",
      "Classical",
      "Country",
      "Electronic",
      "Folk",
      "Gospel",
      "Hip-Hop",
      "Jazz",
      "Latin",
      "Pop",
      "Rap",
      "R&B",
      "Rock",
      "Soul",
    ],
  },
  {
    key: "subGenre",
    label: "Sub-Genre",
    enabled: true,
    items: subGenreByGenre["Hip-Hop"],
  },
  {
    key: "flavor",
    label: "Flavor",
    enabled: true,
    items: [
      "Dark",
      "Aggressive",
      "Gritty",
      "Menacing",
      "Sinister",
      "Haunting",
      "Apocalyptic",
      "Cinematic Dark",
      "Horror",
      "Industrial",
      "Emotional",
      "Melancholic",
      "Nostalgic",
      "Dreamy",
      "Ethereal",
      "Ambient",
      "Atmospheric",
      "Reflective",
      "Introspective",
      "Sentimental",
      "Hype",
      "Explosive",
      "Anthemic",
      "High Energy",
      "Party",
      "Festival",
      "Stadium",
      "Pump-Up",
      "Battle",
      "Victory",
      "Chill",
      "Relaxed",
      "Smooth",
      "Laid Back",
      "Jazzy",
      "Lounge",
      "Mellow",
      "Warm",
      "Cozy",
      "Dream Chill",
      "Futuristic",
      "Cyberpunk",
      "Sci-Fi",
      "Digital",
      "Synthetic",
      "AI-Core",
      "Spacey",
      "Galactic",
      "Neon",
      "Tech Noir",
      "Retro",
      "Vintage",
      "Old School",
      "Analog",
      "Vinyl",
      "Classic",
      "Throwback",
      "Nostalgic 90s",
      "80s Retro",
      "Retro-Futuristic",
      "Experimental",
      "Abstract",
      "Avant-Garde",
      "Chaotic",
      "Glitchy",
      "Psychedelic",
      "Surreal",
      "Progressive",
      "Unpredictable",
      "Artistic",
      "Epic",
      "Heroic",
      "Legendary",
      "Dramatic",
      "Grand",
      "Orchestral",
      "Trailer-Style",
      "Fantasy",
      "Mythic",
      "Adventure",
      "Latin Inspired",
      "Afro Inspired",
      "Asian Fusion",
      "Middle Eastern",
      "Caribbean",
      "Tribal",
      "Island",
      "Mediterranean",
      "Nordic",
      "World Fusion",
      "Playful",
      "Funky",
      "Groovy",
      "Whimsical",
      "Cartoonish",
      "Happy",
      "Quirky",
      "Bouncy",
      "Feel-Good",
      "Silly",
    ],
  },
  {
    key: "mood",
    label: "Mood",
    enabled: true,
    items: [
      "Happy",
      "Joyful",
      "Cheerful",
      "Bright",
      "Playful",
      "Uplifting",
      "Optimistic",
      "Lighthearted",
      "Carefree",
      "Radiant",
      "Sunny",
      "Feel-Good",
      "Jubilant",
      "Sparkling",
      "Fun",
      "Celebratory",
      "Vibrant",
      "Excited",
      "Festive",
      "Blissful",
      "Smiling",
      "Laughing",
      "Whimsical",
      "Warm",
      "Hopeful",
      "Triumphant",
      "Inspired",
      "Encouraging",
      "Charming",
      "Cheerful Bounce",
      "Friendly",
      "Colorful",
      "Delightful",
      "Fresh",
      "Positive",
      "Bright-Eyed",
      "Upbeat",
      "Carefree Summer",
      "Happy-Go-Lucky",
      "Joyous",
      "Romantic",
      "Passionate",
      "Tender",
      "Intimate",
      "Sensual",
      "Loving",
      "Devoted",
      "Dreamy Romance",
      "Soft Love",
      "Gentle Affection",
      "Warm Hearted",
      "Flirtatious",
      "Sweet",
      "Heartfelt",
      "Sentimental",
      "Sincere",
      "Emotional Love",
      "Longing",
      "Soulful Love",
      "Loving Calm",
      "Affectionate",
      "Devotional",
      "Tender Night",
      "Soft Glow",
      "Sweet Memory",
      "Heartwarming",
      "Loving Energy",
      "Gentle Warmth",
      "Deep Love",
      "Romantic Glow",
      "Sad",
      "Melancholic",
      "Heartbroken",
      "Lonely",
      "Somber",
      "Bittersweet",
      "Tearful",
      "Nostalgic",
      "Regretful",
      "Sorrowful",
      "Reflective Sadness",
      "Gloomy",
      "Emotional Pain",
      "Hopeless",
      "Mourning",
      "Quiet Sadness",
      "Fragile",
      "Heavy Heart",
      "Wistful",
      "Pensive",
      "Dark Nostalgia",
      "Soft Grief",
      "Broken",
      "Blue Mood",
      "Hurt",
      "Downcast",
      "Drained",
      "Cold Sadness",
      "Empty",
      "Lost",
      "Quiet Despair",
      "Silent Tears",
      "Emotional Reflection",
      "Melancholy Night",
      "Dark Loneliness",
      "Sad Memories",
      "Lonely Night",
      "Rainy Mood",
      "Reflective Pain",
      "Deep Sorrow",
      "Dark",
      "Sinister",
      "Mysterious",
      "Ominous",
      "Tense",
      "Haunting",
      "Dangerous",
      "Menacing",
      "Suspenseful",
      "Brooding",
      "Creepy",
      "Shadowy",
      "Grim",
      "Apocalyptic",
      "Unsettling",
      "Eerie",
      "Paranoid",
      "Threatening",
      "Dark Cinematic",
      "Heavy Atmosphere",
      "Intense",
      "Aggressive Mood",
      "Dark Power",
      "Gothic",
      "Villainous",
      "Dark Energy",
      "Stormy Mood",
      "Chaotic Mood",
      "Foreboding",
      "Dreadful",
      "Calm",
      "Peaceful",
      "Relaxed",
      "Chill",
      "Serene",
      "Tranquil",
      "Smooth",
      "Dreamy",
      "Airy",
      "Floating",
      "Quiet",
      "Gentle",
      "Soft",
      "Lazy",
      "Comfortable",
      "Warm Chill",
      "Cozy",
      "Slow Night",
      "Soothing",
      "Lush",
      "Velvet Calm",
      "Midnight Chill",
      "Hazy",
      "Cool Breeze",
      "Relaxing Flow",
      "Slow Motion",
      "Drift Mood",
      "Ambient Calm",
      "Smooth Lounge",
      "Late Night",
      "Epic",
      "Heroic",
      "Dramatic",
      "Grand",
      "Legendary",
      "Powerful",
      "Triumphant",
      "Majestic",
      "Cinematic",
      "Anthemic",
      "Monumental",
      "Battle Ready",
      "Victorious",
      "Warrior Spirit",
      "Determined",
      "Fearless",
      "Noble",
      "Intense Drama",
      "Rising Tension",
      "Climactic",
      "Massive",
      "World-Shaking",
      "Destiny Mood",
      "Commanding",
      "Unstoppable",
      "Bold",
      "Thunderous",
      "Mythic",
      "Rising Power",
      "Final Victory",
    ],
  },
  {
    key: "tempo",
    label: "Tempo",
    enabled: true,
    items: [
      "68 BPM",
      "74 BPM",
      "82 BPM",
      "96 BPM",
      "108 BPM",
      "118 BPM",
      "126 BPM",
      "132 BPM",
      "140 BPM",
      "154 BPM",
      "half-time 150 BPM",
      "free tempo intro into 120 BPM",
    ],
  },
  {
    key: "energy",
    label: "Energy",
    enabled: true,
    items: [
      "Explosive",
      "Intense",
      "Aggressive",
      "Furious",
      "Wild",
      "Hyper",
      "Chaotic",
      "Relentless",
      "Electrifying",
      "Ferocious",
      "Unstoppable",
      "Blazing",
      "Storming",
      "Thunderous",
      "Roaring",
      "Adrenaline Rush",
      "Frenzied",
      "Volatile",
      "Reckless",
      "Rampaging",
      "Hard-Hitting",
      "Pulse-Pounding",
      "Riotous",
      "Savage",
      "Fiery",
      "Unleashed",
      "Overdriven",
      "Turbocharged",
      "Crashing",
      "Breakneck",
      "Supercharged",
      "Power Surge",
      "Maximum Intensity",
      "Blistering",
      "Thunderstrike",
      "Sonic Boom",
      "Rampant Energy",
      "Lightning Fast",
      "Overheated",
      "Hyperdrive",
      "Driving",
      "Pumping",
      "High-Octane",
      "Fast-Paced",
      "Dynamic",
      "Propulsive",
      "Energized",
      "Vibrant",
      "Spirited",
      "Lively",
      "Charged",
      "Punchy",
      "Rhythmic",
      "Momentum",
      "Hard Grooving",
      "High Gear",
      "Pulsing",
      "Electric",
      "Jumping",
      "Revved Up",
      "Booming",
      "Shaking",
      "Hyped",
      "Fired Up",
      "Motion-Filled",
      "Rapid Flow",
      "Hard Driving Beat",
      "Kinetic",
      "Blazing Rhythm",
      "Dynamic Push",
      "Forward Motion",
      "Heavy Pulse",
      "Amped Up",
      "Rapid Fire",
      "High Voltage",
      "Grooving Hard",
      "Charging",
      "Galloping",
      "Racing",
      "Thumping",
      "Party Energy",
      "Celebratory",
      "Festive",
      "Joyful Burst",
      "Carefree",
      "Playful",
      "Bouncy",
      "Dancefloor",
      "Club Energy",
      "Euphoric",
      "Feel-Good",
      "Sunshine Energy",
      "Summer Vibes",
      "Carnival Energy",
      "Uplifting",
      "Happy Rush",
      "Festival Energy",
      "Radiant",
      "Sparkling",
      "Lighthearted",
      "Cheeky",
      "Groovy",
      "Funky Bounce",
      "Electric Joy",
      "Wild Fun",
      "Party Anthem",
      "Colorful Energy",
      "Glittering",
      "Laughing Energy",
      "Weekend Energy",
      "Groovy",
      "Smooth Groove",
      "Swinging",
      "Funky Pulse",
      "Steady Flow",
      "Head-Nodding",
      "Mid-Tempo Drive",
      "Cool Energy",
      "Slick Rhythm",
      "Balanced Energy",
      "Rolling Beat",
      "Laid-Back Groove",
      "Smooth Motion",
      "Chill Bounce",
      "Easy Rhythm",
      "Flowing Groove",
      "Casual Energy",
      "Floating Rhythm",
      "Warm Pulse",
      "Soft Drive",
      "Gliding Energy",
      "Subtle Groove",
      "Steady Pulse",
      "Urban Groove",
      "Soulful Motion",
      "Relaxed Beat",
      "Jazzy Energy",
      "R&B Groove",
      "Midnight Groove",
      "Late Night Flow",
      "Calm",
      "Relaxed",
      "Gentle",
      "Soft",
      "Dreamy",
      "Airy",
      "Floating",
      "Serene",
      "Peaceful",
      "Quiet",
      "Smooth Chill",
      "Slow Burn",
      "Drifting",
      "Ambient Energy",
      "Hazy",
      "Mellow",
      "Tender",
      "Soft Pulse",
      "Warm Calm",
      "Tranquil",
      "Lazy Flow",
      "Deep Relaxation",
      "Soothing",
      "Lush Calm",
      "Cool Breeze",
      "Nighttime Calm",
      "Restful",
      "Velvet Energy",
      "Slow Motion",
      "Calm Waves",
      "Epic Build",
      "Rising Power",
      "Heroic Surge",
      "Dramatic Tension",
      "Grand Energy",
      "Legendary Power",
      "Thunderous Build",
      "Battle Energy",
      "Warrior Spirit",
      "Anthemic Power",
      "Massive Sound",
      "Cinematic Pulse",
      "Towering Energy",
      "Exploding Finale",
      "Rising Storm",
      "Monumental Power",
      "Dark Intensity",
      "Mythic Energy",
      "Heroic Drive",
      "Destiny Energy",
      "Titanic Power",
      "Apocalyptic Force",
      "World-Shaking",
      "Galactic Energy",
      "Epic Momentum",
      "Victory Energy",
      "War Drums",
      "Thunder March",
      "Final Stand",
      "Climactic Energy",
    ],
  },
  {
    key: "texture",
    label: "Texture",
    enabled: true,
    items: [
      "dusty tape haze",
      "granular shimmer",
      "crushed transients",
      "wide glassy pads",
      "broken speaker distortion",
      "detuned analog wash",
      "metallic resonance",
      "underwater filtering",
      "air-filled top end",
      "fuzzy harmonic bloom",
      "narrow mono center with wide tails",
    ],
  },
  {
    key: "instrumentation",
    label: "Instrumentation",
    enabled: true,
    items: [
      "Acoustic guitar",
      "Nylon string guitar",
      "Steel string guitar",
      "Twelve-string guitar",
      "Flamenco guitar",
      "Resonator guitar",
      "Banjo",
      "Mandolin",
      "Ukulele",
      "Lute",
      "Oud",
      "Sitar",
      "Bouzouki",
      "Balalaika",
      "Charango",
      "Harp",
      "Harpsichord",
      "Piano",
      "Grand piano",
      "Upright piano",
      "Honky-tonk piano",
      "Prepared piano",
      "Toy piano",
      "Electric piano",
      "Rhodes piano",
      "Wurlitzer piano",
      "Clavinet",
      "Accordion",
      "Concertina",
      "Harmonium",
      "Organ",
      "Pipe organ",
      "Hammond organ",
      "Violin",
      "Viola",
      "Cello",
      "Double bass",
      "String ensemble",
      "Fiddle",
      "Hardanger fiddle",
      "Trumpet",
      "Trombone",
      "French horn",
      "Tuba",
      "Flugelhorn",
      "Clarinet",
      "Bass clarinet",
      "Oboe",
      "English horn",
      "Bassoon",
      "Flute",
      "Piccolo",
      "Alto flute",
      "Bass flute",
      "Pan flute",
      "Recorder",
      "Didgeridoo",
      "Bagpipes",
      "Duduk",
      "Shakuhachi",
      "Erhu",
      "Koto",
      "Shamisen",
      "Kalimba",
      "Mbira",
      "Hang drum",
      "Handpan",
      "Steel tongue drum",
      "Marimba",
      "Vibraphone",
      "Xylophone",
      "Glockenspiel",
      "Tubular bells",
      "Celesta",
      "Cajón",
      "Bongos",
      "Congas",
      "Djembe",
      "Frame drum",
      "Bodhrán",
      "Taiko drum",
      "Tabla",
      "Darbuka",
      "Shaker",
      "Tambourine",
      "Triangle",
      "Claves",
      "Cowbell",
      "Woodblock",
      "Log drum",
      "Finger snaps",
      "Hand claps",
      "Foot stomps",
      "Wind chimes",
      "Bell chimes",
      "Temple bells",
      "Singing bowls",
      "Waterphone",
      "Slide whistle",
      "Train whistle",
      "Electric guitar clean",
      "Electric guitar crunch",
      "Electric guitar distortion",
      "Fuzz guitar",
      "Slide guitar",
      "Guitar harmonics",
      "Palm-muted guitar",
      "Tremolo guitar",
      "Guitar feedback",
      "Guitar swells",
      "Guitar delay layers",
      "Guitar shimmer",
      "Guitar chorus tone",
      "Guitar phaser tone",
      "Electric bass",
      "Slap bass",
      "Fretless bass",
      "Distorted bass",
      "Bass harmonics",
      "Bass drones",
      "Drum kit",
      "Kick drum",
      "Snare drum",
      "Hi-hat",
      "Ride cymbal",
      "Crash cymbal",
      "Tom drums",
      "Brush drums",
      "Drum machine",
      "Electronic drums",
      "Breakbeat drums",
      "Trap hi-hats",
      "Funk groove drums",
      "Rock drums",
      "Jazz brushes",
      "Rimshots",
      "Drum fills",
      "Drum loops",
      "Drum breaks",
      "Drum hits",
      "Drum impacts",
      "Drum risers",
      "Drum sweeps",
      "Reverse drums",
      "Drum ambience",
      "Drum distortion",
      "Drum saturation",
      "Drum compression pump",
      "Kick layering",
      "Snare layering",
      "Clap stacks",
      "Drum bus saturation",
      "Drum room ambience",
      "Cymbal swells",
      "Drum crescendo rolls",
      "Percussion loops",
      "Hybrid percussion",
      "Stadium drums",
      "War drums",
      "Cinematic drums",
      "Analog synth lead",
      "Digital synth lead",
      "Mono synth lead",
      "Poly synth lead",
      "Supersaw lead",
      "Trance lead",
      "Acid synth",
      "FM synth",
      "Modular synth",
      "Granular synth",
      "Bitcrushed synth",
      "Glitch synth",
      "Synth pad warm",
      "Ambient synth pad",
      "Choir synth pad",
      "String synth pad",
      "Dark synth pad",
      "Evolving synth pad",
      "Drone synth",
      "Ambient drone synth",
      "Synth pluck",
      "EDM pluck",
      "Synth harp pluck",
      "Arpeggiated synth",
      "Sequencer synth",
      "Laser synth",
      "Sci-fi synth",
      "Cyber synth",
      "Arcade synth",
      "Retro synthwave lead",
      "Vaporwave pad",
      "Lo-fi synth",
      "Synth bells",
      "Synth brass",
      "Synth choir",
      "Synth strings",
      "Detuned synth",
      "Saw wave synth",
      "Square wave synth",
      "Triangle wave synth",
      "Pulse wave synth",
      "Sub bass",
      "808 bass",
      "Reese bass",
      "Wobble bass",
      "Dubstep growl bass",
      "Neuro bass",
      "Future bass synth",
      "Analog bass synth",
      "Digital bass synth",
      "Filter sweep synth",
      "LFO wobble synth",
      "Resonant synth",
      "Portamento synth",
      "Gliding synth",
      "Digital bleeps",
      "Computer beep synth",
      "Robotic synth",
      "Alien synth tone",
      "Space synth pad",
      "Cosmic synth drone",
      "Ambient synth bed",
      "Hybrid orchestral synth",
      "Hybrid synth strings",
      "Hybrid synth brass",
      "Synthetic percussion",
      "Synthetic drums",
      "Synth impacts",
      "Riser synth",
      "Downlifter synth",
      "Glitch pulses",
      "Random synth pattern",
      "Modular drone",
      "Analog pad stack",
      "Supersaw pad",
      "Filtered pad sweep",
      "Detuned pad stack",
      "Pulsing synth rhythm",
      "Sidechained synth pad",
      "Stereo synth spread",
      "Atmospheric synth texture",
      "Dark electronic drone",
      "Futuristic synth ambience",
      "Neon synth tone",
      "Holographic synth",
      "Cyberpunk synth pad",
      "Digital glitch texture",
      "Synth shimmer pad",
      "Floating synth layer",
      "Expansive synth soundscape",
      "Orchestral strings legato",
      "Strings spiccato",
      "Strings staccato",
      "Strings tremolo",
      "Strings pizzicato",
      "Chamber strings",
      "Epic string ensemble",
      "Suspense strings",
      "Horror strings",
      "Brass ensemble",
      "Epic brass hits",
      "Low brass blasts",
      "Horn section swells",
      "War horn calls",
      "Timpani rolls",
      "Taiko hits",
      "Battle drums",
      "Trailer impacts",
      "Cinematic booms",
      "Sub impacts",
      "Orchestral risers",
      "Orchestral downlifters",
      "Choir male",
      "Choir female",
      "Gregorian choir",
      "Epic choir chants",
      "Choir whispers",
      "Choir drones",
      "Choir pads",
      "Choir echoes",
      "Orchestral harp gliss",
      "Fantasy harp plucks",
      "Celesta sparkles",
      "Glass harmonica",
      "Cinematic pulses",
      "Cinematic drones",
      "Orchestra ambience",
      "Orchestra hits",
      "Orchestra swells",
      "Orchestra crescendos",
      "Orchestra clusters",
      "Orchestra tension bed",
      "Orchestra ostinato",
      "Orchestra runs",
      "Brass stabs",
      "Brass swells",
      "Low brass growls",
      "Epic brass stack",
      "Massive orchestra hits",
      "Cinematic drum ensemble",
      "Trailer braams",
      "Epic finale orchestra",
      "Dramatic string stabs",
      "Hybrid orchestra synth",
      "Orchestra percussion hits",
      "Orchestra impacts",
      "Dark orchestral drones",
      "Rising orchestral tension",
      "Epic orchestral build",
      "Heroic orchestra swell",
      "Massive cinematic wall",
      "Orchestral tension pulses",
      "Cinematic choir rise",
      "Orchestra thunder hits",
      "Hybrid cinematic percussion",
      "Orchestral sweep",
      "Cinematic ambience bed",
      "Fantasy orchestral layer",
      "Mythic orchestral tone",
      "Epic cinematic drones",
      "Cinematic tension hits",
      "Orchestra finale crash",
      "Choir crescendo",
      "Choir impact hit",
      "Orchestra build swell",
      "Cinematic stingers",
      "Epic orchestral stabs",
      "Orchestra climax hit",
      "Cinematic final boom",
      "Grand orchestral ending",
      "Rain ambience",
      "Heavy rain",
      "Light rain",
      "Thunderstorm",
      "Wind gusts",
      "Ocean waves",
      "River flow",
      "Water dripping",
      "Water splashes",
      "Campfire crackling",
      "Fire roaring",
      "Forest ambience",
      "Jungle ambience",
      "Desert wind",
      "Snow crunch",
      "Ice cracking",
      "Avalanche rumble",
      "Volcano rumble",
      "Earthquake rumble",
      "City ambience",
      "Busy street",
      "Traffic noise",
      "Car passing",
      "Train passing",
      "Train station ambience",
      "Airplane flyover",
      "Airport ambience",
      "Subway ambience",
      "Market ambience",
      "Crowd cheering",
      "Crowd chanting",
      "Crowd murmurs",
      "Applause",
      "Stadium crowd",
      "Festival crowd",
      "Footsteps gravel",
      "Footsteps grass",
      "Footsteps wood floor",
      "Footsteps hallway echo",
      "Door creak",
      "Door slam",
      "Metal clang",
      "Machinery hum",
      "Engine rumble",
      "Mechanical clicks",
      "Clock ticking",
      "Clock chime",
      "Church bells",
      "Wind chimes",
      "Paper rustle",
      "Page turning",
      "Typewriter typing",
      "Keyboard typing",
      "Camera shutter",
      "Polaroid eject",
      "Tape rewind",
      "Tape stop",
      "Cassette click",
      "Vinyl crackle",
      "Cassette hiss",
      "Tape flutter",
      "Radio static",
      "Walkie talkie audio",
      "Phone call filter",
      "Megaphone voice",
      "Alarm beep",
      "Notification ping",
      "Computer boot sound",
      "Electric hum",
      "Neon buzz",
      "Transformer buzz",
      "Power surge sound",
      "Spark crack",
      "Sonic boom",
      "Jet flyby",
      "Helicopter blades",
      "Siren wail",
      "Police radio chatter",
      "Distant thunder",
      "Cave echo",
      "Cathedral ambience",
      "Tunnel echo",
      "Stadium echo",
      "Concert hall ambience",
      "Church ambience",
      "Library ambience",
      "Classroom ambience",
      "Restaurant ambience",
      "Night street ambience",
      "Midnight city ambience",
      "Ambient drones",
      "Deep sub drones",
      "High frequency drones",
      "Reverse ambience",
      "Reverse piano",
      "Reverse guitar",
      "Reverse cymbal",
      "Reverse impacts",
      "Whoosh transitions",
      "Air sweeps",
      "Sonic sweeps",
      "Filter sweeps",
      "White noise",
      "Pink noise",
      "Brown noise",
      "Static noise",
      "Digital artifacts",
      "Glitch noise",
      "Bitcrushed noise",
      "Distortion textures",
      "Tape saturation",
      "Analog warmth noise",
      "Granular sound clouds",
      "Reverb clouds",
      "Delay trails",
      "Shimmer reverb",
      "Stereo widening texture",
      "Mono collapse effect",
      "Doppler fly-by effect",
      "Sidechain pumping texture",
      "Gated reverb",
      "Phaser wash",
      "Flanger sweep",
      "Chorus wash",
      "Stutter effect",
      "Glitch stutter",
      "Granular time stretch",
      "Time stretch artifacts",
      "Pitch-shift textures",
      "Formant shifting",
      "Vocal chop textures",
      "Reverse vocal textures",
      "Whisper layers",
      "Breathing textures",
      "Heartbeat thump",
      "Sub rumble",
      "Low frequency rumble",
      "Cinematic tension bed",
      "Atmosphere pad",
      "Floating ambience",
      "Dream ambience",
      "Dark ambience",
      "Horror ambience",
      "Cosmic ambience",
      "Space ambience",
      "Sci-fi ambience",
      "Alien soundscape",
      "Futuristic ambience",
      "Cyber ambience",
      "Neon ambience",
      "Digital rain ambience",
      "Electric storm texture",
      "Atmospheric bed",
      "Expansive soundscape",
      "Sonic cloud texture",
      "Deep ambience layer",
      "Floating sonic layer",
      "Subtle environmental bed",
      "Cinematic background ambience",
      "Wide stereo ambience",
      "Surround ambience field",
      "Atmospheric shimmer",
      "Resonant harmonic layer",
      "Sonic atmosphere pad",
      "Ambient tonal wash",
      "Evolving ambience layer",
      "Soundscape texture",
      "Immersive ambience field",
      "Expansive sonic texture",
      "Infinite ambience layer",
    ],
  },
  {
    key: "fx",
    label: "FX",
    enabled: true,
    items: [
      "Reverb",
      "Hall reverb",
      "Room reverb",
      "Plate reverb",
      "Spring reverb",
      "Shimmer reverb",
      "Reverse reverb",
      "Infinite reverb",
      "Convolution reverb",
      "Cathedral reverb",
      "Chamber reverb",
      "Arena reverb",
      "Slapback echo",
      "Stereo delay",
      "Ping-pong delay",
      "Tape delay",
      "Analog delay",
      "Digital delay",
      "Multi-tap delay",
      "Dub delay",
      "Echo tail",
      "Delay throw",
      "Delay feedback swell",
      "Reverb swell",
      "Reverb bloom",
      "Reverb freeze",
      "Reverse echo",
      "Ghost echo",
      "Infinite echo",
      "Delay smear",
      "Echo trails",
      "Reverb wash",
      "Reverb cloud",
      "Reverb gate",
      "Reverse room reverb",
      "Reverse hall reverb",
      "Tape echo wobble",
      "Slap delay",
      "Ambient echo layer",
      "Echo slap modulation",
      "Reverb shimmer stack",
      "Subtle room ambience",
      "Large space reverb",
      "Reverse delay tail",
      "Blooming echo",
      "Stereo echo spread",
      "Feedback echo loop",
      "Delay saturation",
      "Echo distortion",
      "Dub echo feedback",
      "Tape echo saturation",
      "Delay pitch drift",
      "Reverse delay feedback",
      "Reverb pulse",
      "Reverb sidechain",
      "Ambient echo wash",
      "Reverb rise",
      "Reverb fall",
      "Echo modulation",
      "Delay smear ambience",
      "Chorus",
      "Flanger",
      "Phaser",
      "Tremolo",
      "Vibrato",
      "Rotary speaker",
      "Auto-pan",
      "Ensemble chorus",
      "Stereo widener",
      "Haas delay",
      "Micro pitch shift",
      "Pitch detune",
      "Wow effect",
      "Flutter effect",
      "Leslie cabinet",
      "Harmonic tremolo",
      "Modulated delay",
      "Rotary swirl",
      "Stereo swirl",
      "Phaser sweep",
      "Flanger sweep",
      "Chorus shimmer",
      "Phase inversion FX",
      "Stereo wobble",
      "Doppler modulation",
      "Orbit panning",
      "Pan rotation",
      "Oscillating pan",
      "Wave pan",
      "Modulated filter sweep",
      "LFO modulation",
      "Pulse modulation",
      "Frequency wobble",
      "Rotary echo",
      "Phaser resonance",
      "Chorus depth expansion",
      "Flanger resonance",
      "Modulated reverb",
      "Tremolo gating",
      "Vibrato pitch drift",
      "Stereo chorus widening",
      "Phaser pulse",
      "Filter tremolo",
      "Rotary pitch modulation",
      "Modulated stereo delay",
      "Pan stutter",
      "Slow phase sweep",
      "Fast phase sweep",
      "LFO stereo motion",
      "Harmonic chorus layer",
      "Vibrato shimmer",
      "Phaser echo blend",
      "Rotary surround",
      "Wide stereo modulation",
      "Oscillating stereo shift",
      "Dual chorus effect",
      "Multi-phase layering",
      "Stereo flutter effect",
      "Rotating ambience",
      "Modulated ambience bed",
      "Distortion",
      "Overdrive",
      "Fuzz distortion",
      "Tube saturation",
      "Tape saturation",
      "Analog saturation",
      "Bitcrusher",
      "Downsampling distortion",
      "Soft clipping",
      "Hard clipping",
      "Amp simulation",
      "Cabinet simulation",
      "Lo-fi distortion",
      "Vinyl distortion",
      "Cassette distortion",
      "Speaker breakup",
      "Crunch distortion",
      "Harmonic distortion",
      "Drive boost",
      "Grit layer",
      "Distorted ambience",
      "Distorted reverb tail",
      "Saturated echo",
      "Tube warmth effect",
      "Vintage saturation",
      "Tape overdrive",
      "Saturated bass",
      "Distorted synth",
      "Distorted vocal layer",
      "Harmonic excitation",
      "Overdriven echo",
      "Saturated drums",
      "Fuzz bass",
      "Distortion sweep",
      "Bitcrushed ambience",
      "Digital distortion",
      "Wave shaping distortion",
      "Analog clipping",
      "Grit delay",
      "Saturated ambience",
      "Warm distortion tone",
      "Drive modulation",
      "Tape crunch",
      "Cassette wobble distortion",
      "Analog grit bed",
      "Saturated reverb cloud",
      "Harmonic fuzz layer",
      "Distorted noise layer",
      "Fuzzed ambience wash",
      "Tube warmth echo",
      "Distortion burst",
      "Distorted sweep",
      "Saturated noise floor",
      "Overdriven ambience",
      "Harmonic saturation cloud",
      "Distorted stereo spread",
      "Fuzzed transition hit",
      "Drive swell",
      "Distortion pulse",
      "Saturated harmonic layer",
      "Low-pass filter",
      "High-pass filter",
      "Band-pass filter",
      "Notch filter",
      "Filter sweep up",
      "Filter sweep down",
      "Resonant filter",
      "Auto filter",
      "Wah effect",
      "Auto wah",
      "Talkbox",
      "Formant filter",
      "Telephone filter",
      "Megaphone filter",
      "Radio filter",
      "Narrow band filter",
      "Comb filter",
      "Morph filter",
      "Tonal morphing",
      "Sweep resonance",
      "Filter oscillation",
      "Filter pulsing",
      "Filter modulation",
      "Filter stutter",
      "Sweeping resonance layer",
      "Analog filter drift",
      "Digital filter glitch",
      "Filter gating",
      "Band filter sweep",
      "LFO filter pulse",
      "Resonant sweep FX",
      "Filter morph pad",
      "Sub filter sweep",
      "Filter echo blend",
      "Auto resonance shift",
      "Dynamic filter gate",
      "Tone shaping sweep",
      "Moving band filter",
      "Sweeping tone morph",
      "Filter ripple effect",
      "Auto formant shift",
      "Filter envelope",
      "Pulse filter modulation",
      "Stereo filter motion",
      "Wide filter sweep",
      "Dual filter sweep",
      "Filter swirl effect",
      "Phase filter layer",
      "Filter depth modulation",
      "Tonal drift effect",
      "Filter bloom",
      "Filter pulse echo",
      "Morph resonance",
      "Oscillating filter layer",
      "Filter resonance shimmer",
      "Filter rise transition",
      "Filter drop transition",
      "Filter swell ambience",
      "Dynamic tonal sweep",
      "Harmonic filter cloud",
      "Pitch shifting",
      "Pitch bend",
      "Auto-Tune",
      "Hard tuning",
      "Vocal tuning",
      "Harmonizer",
      "Octaver",
      "Pitch doubling",
      "Formant shifting",
      "Gender morphing",
      "Vocal doubling",
      "Vocal layering",
      "Vocal widening",
      "Whisper vocal layer",
      "Reverse vocal",
      "Vocal chop",
      "Stutter vocal",
      "Glitch vocal",
      "Vocoder",
      "Robot voice",
      "Pitch drift effect",
      "Pitch swell",
      "Pitch flutter",
      "Vocal shimmer layer",
      "Harmony stack",
      "Choir harmonizer",
      "Vocal echo layer",
      "Reverse vocal ambience",
      "Vocal freeze effect",
      "Formant glide",
      "Vocal morph",
      "Pitch stutter",
      "Pitch glitch burst",
      "Harmonized echo",
      "Octave shimmer",
      "Vocal glitch cloud",
      "Vocoder choir",
      "Synthetic voice layer",
      "Pitch echo swirl",
      "Vocal pitch fall",
      "Vocal pitch rise",
      "Dual harmony effect",
      "Layered harmony wall",
      "Pitch echo tails",
      "Vocal resonance FX",
      "Whisper ambience layer",
      "Vocal distortion FX",
      "Vocal tape stop",
      "Vocal pitch wobble",
      "Vocal modulation FX",
      "Pitch glide ambience",
      "Harmonized delay",
      "Vocoder shimmer",
      "Layered robotic choir",
      "Pitch freeze cloud",
      "Vocal echo bloom",
      "Harmony swell",
      "Pitch echo delay",
      "Vocal shimmer wash",
      "Pitch morph ambience",
      "Stutter edit",
      "Beat repeat",
      "Buffer repeat",
      "Tape stop",
      "Tape start",
      "Time-stretch artifact",
      "Granular stretch",
      "Digital skipping",
      "CD skip effect",
      "Data glitch",
      "Pixelated audio",
      "Static burst",
      "Noise burst",
      "Circuit-bent glitch",
      "Freeze buffer",
      "Micro-loop glitch",
      "Digital crackle",
      "Glitch pulse",
      "Buffer glitch swirl",
      "Reverse glitch",
      "Data corruption sound",
      "Digital fragmentation",
      "Stutter gate",
      "Granular cloud FX",
      "Time slice glitch",
      "Random glitch burst",
      "Digital distortion pulse",
      "Micro glitch ticks",
      "Granular ambience bed",
      "Data noise crackle",
      "Digital bit noise",
      "Fragmented echo glitch",
      "Loop stutter FX",
      "Reverse glitch pulse",
      "Micro data burst",
      "Frozen glitch layer",
      "Data stutter",
      "Buffer scatter",
      "Granular time slice",
      "Digital glitch ambience",
      "Randomized glitch sweep",
      "Glitch modulation",
      "Stutter echo",
      "Glitch riser",
      "Glitch downer",
      "Buffer echo layer",
      "Digital scramble FX",
      "Corrupted audio burst",
      "Bit scatter effect",
      "Loop fragmentation",
      "Data freeze",
      "Glitch cloud ambience",
      "Random bitcrush glitch",
      "Circuit glitch pulse",
      "Micro glitch swarm",
      "Data distortion sweep",
      "Glitch flicker",
      "Fragmented pitch glitch",
      "Data crackle ambience",
      "Digital artifact cloud",
      "Riser",
      "Downlifter",
      "Whoosh",
      "Reverse cymbal",
      "Cymbal swell",
      "Reverse crash",
      "Impact hit",
      "Sub drop",
      "Bass drop",
      "Boom hit",
      "Snare build",
      "Drum build FX",
      "Noise riser",
      "Tonal riser",
      "Tonal downer",
      "Reverse piano hit",
      "Reverse drum hit",
      "Drop silence",
      "Sweep transition",
      "Reverse ambience swell",
      "Cymbal reverse swell",
      "Impact boom",
      "Cinematic slam",
      "Deep impact hit",
      "Rising tension sweep",
      "Noise sweep",
      "Reverse noise build",
      "Bass rumble rise",
      "Sub rumble sweep",
      "Snare crescendo build",
      "Transition boom",
      "Reverse impact hit",
      "Atmospheric riser",
      "Tension riser sweep",
      "Impact echo hit",
      "Reverse boom hit",
      "Down sweep drop",
      "Noise burst drop",
      "Sonic slam",
      "Bass impact echo",
      "Cymbal crash swell",
      "Reverse snare hit",
      "Reverse clap swell",
      "Reverse ambience burst",
      "Reverse noise hit",
      "Transition rumble",
      "Impact echo bloom",
      "Reverse sub drop",
      "Whoosh burst",
      "Air sweep FX",
      "Sonic boom FX",
      "Riser echo tail",
      "Impact reverb tail",
      "Transition sweep burst",
      "Drop silence pause",
      "Sonic burst transition",
      "Impact swell FX",
      "Reverse echo sweep",
      "Bass rumble drop",
      "Final impact crash",
      "Vinyl crackle",
      "Tape hiss",
      "Cassette wobble",
      "Radio static",
      "Electric hum",
      "Neon buzz",
      "Crowd cheering",
      "Applause",
      "Footsteps",
      "Door creak",
      "Clock ticking",
      "Heartbeat",
      "Rain ambience",
      "Thunder ambience",
      "Wind ambience",
      "Fire crackle",
      "Water drip",
      "Ocean waves",
      "City ambience",
      "Birds ambience",
      "Cave echo",
      "Cathedral ambience",
      "Tunnel echo",
      "Stadium echo",
      "Market crowd ambience",
      "Night city ambience",
      "Festival crowd",
      "Mechanical hum",
      "Engine rumble",
      "Train pass sound",
      "Airplane flyover",
      "Helicopter blades",
      "Police siren",
      "Alarm beep",
      "Notification ping",
      "Camera shutter",
      "Page turn",
      "Keyboard typing",
      "Paper rustle",
      "Glass shatter FX",
      "Metal clang FX",
      "Industrial hit FX",
      "Machine gear noise",
      "Electric spark",
      "Power surge crack",
      "Storm wind gust",
      "Distant thunder",
      "Campfire ambience",
      "Water splash",
      "River ambience",
      "Forest ambience",
      "Jungle ambience",
      "Desert wind",
      "Snow crunch",
      "Ice cracking",
      "Avalanche rumble",
      "Volcano rumble",
      "Earthquake rumble",
      "Sonic boom",
      "Doppler fly-by",
      "Surround pan sweep",
      "Orbiting sound FX",
      "Stereo echo throw",
      "Receding echo tail",
      "Wide ambience bloom",
      "Spatial shimmer",
      "Depth layering FX",
      "Surround movement FX",
      "Distance simulation FX",
      "Expanding stereo field",
      "Collapsing stereo field",
      "Rotating pan swirl",
      "3D panning movement",
      "Binaural spatial motion",
      "Sonic atmosphere bed",
      "Ambient noise cloud",
      "Atmospheric texture wash",
      "Deep ambience layer",
      "Cinematic background ambience",
      "Infinite soundscape FX",
    ],
  },
  {
    key: "environment",
    label: "Environment",
    enabled: false,
    items: [
      "abandoned station at 3 AM",
      "rain hitting neon pavement",
      "satellite drift over a dead city",
      "warehouse after the crowd leaves",
      "frozen coastline at dawn",
      "elevator to a hidden club",
      "desert highway under sodium lights",
      "storm cellar full of humming wires",
      "foggy rooftop overlooking traffic",
    ],
  },
  {
    key: "rhythm",
    label: "Rhythm",
    enabled: true,
    items: [
      "swinging off-grid hats",
      "tight four-on-the-floor kick",
      "broken beat syncopation",
      "triplet hi-hat accents",
      "staggered percussion fills",
      "ghost-kick momentum",
      "shuffling garage drums",
      "tom-led tribal movement",
      "snare gaps that create tension",
      "double-time fill transitions",
    ],
  },
  {
    key: "structure",
    label: "Structure",
    enabled: true,
    items: [
      "Verse - Chorus - Verse - Chorus - Bridge - Chorus",
      "Verse - Chorus - Verse - Chorus - Chorus",
      "Verse - Chorus - Verse - Chorus - Outro",
      "Intro - Verse - Chorus - Verse - Chorus - Bridge - Chorus",
      "Intro - Verse - Pre-Chorus - Chorus - Verse - Pre-Chorus - Chorus - Bridge - Chorus",
      "Verse - Pre-Chorus - Chorus - Verse - Pre-Chorus - Chorus - Outro",
      "Verse - Chorus - Verse - Chorus - Bridge - Final Chorus",
      "Verse - Chorus - Chorus - Bridge - Chorus",
      "Intro - Verse - Chorus - Verse - Chorus - Chorus - Outro",
      "Verse - Chorus - Bridge - Chorus",
      "Intro - Verse - Pre-Chorus - Chorus - Verse - Pre-Chorus - Chorus - Bridge - Chorus - Outro",
      "Intro - Verse - Chorus - Verse - Chorus - Bridge - Chorus - Outro",
      "Verse - Chorus - Verse - Chorus - Instrumental - Chorus",
      "Intro - Verse - Chorus - Chorus - Bridge - Chorus",
      "Verse - Chorus - Verse - Chorus - Breakdown - Chorus",
      "Verse - Pre-Chorus - Chorus - Post-Chorus - Verse - Pre-Chorus - Chorus - Bridge - Chorus",
      "Intro - Chorus - Verse - Chorus - Bridge - Chorus",
      "Verse - Chorus - Verse - Chorus - Instrumental Break - Chorus",
      "Intro - Verse - Chorus - Bridge - Chorus - Outro",
      "Verse - Chorus - Verse - Chorus - Extended Outro",
      "Intro - Verse - Hook - Verse - Hook - Verse - Hook - Outro",
      "Intro - Hook - Verse - Hook - Verse - Hook - Outro",
      "Intro - Verse - Hook - Verse - Hook - Bridge - Hook",
      "Hook - Verse - Hook - Verse - Hook",
      "Intro - Verse - Verse - Hook - Verse - Hook",
      "Intro - Hook - Verse - Verse - Hook - Outro",
      "Intro - Verse - Hook - Verse - Hook - Outro",
      "Hook - Verse - Hook - Verse - Bridge - Hook",
      "Intro - Verse - Hook - Verse - Hook - Verse - Hook",
      "Intro - Verse - Hook - Verse - Hook - Bridge - Hook - Outro",
      "Intro - Verse - Chorus - Verse - Chorus - Guitar Solo - Chorus",
      "Intro - Verse - Chorus - Verse - Chorus - Solo - Bridge - Chorus",
      "Intro - Verse - Verse - Chorus - Verse - Chorus - Outro",
      "Intro - Verse - Chorus - Instrumental - Chorus",
      "Verse - Chorus - Verse - Chorus - Solo - Chorus",
      "Intro - Verse - Chorus - Verse - Chorus - Extended Solo - Chorus",
      "Intro - Verse - Chorus - Bridge - Chorus - Solo - Chorus",
      "Verse - Chorus - Verse - Chorus - Bridge - Outro",
      "Intro - Verse - Chorus - Chorus - Solo - Chorus",
      "Intro - Verse - Chorus - Verse - Chorus - Jam - Outro",
      "Intro - Verse - Instrumental - Verse - Outro",
      "Instrumental - Verse - Chorus - Instrumental - Chorus",
      "Verse - Verse - Chorus - Chorus - Bridge - Chorus",
      "Intro - Build - Drop - Verse - Drop - Bridge - Drop",
      "Verse - Build - Chorus - Breakdown - Chorus",
      "Intro - Instrumental - Verse - Chorus - Instrumental - Chorus",
      "Intro - Spoken Word - Verse - Chorus - Outro",
      "Instrumental - Verse - Verse - Chorus - Outro",
      "Intro - Chorus - Verse - Bridge - Chorus - Outro",
      "Continuous Build (no repeating sections)",
    ],
  },
  {
    key: "vocalStyle",
    label: "Vocal Style",
    enabled: false,
    items: [
      "Soft singing",
      "Breath vocal",
      "Whisper vocal",
      "Gentle vocal",
      "Smooth vocal",
      "Tender vocal",
      "Light vocal",
      "Airy vocal",
      "Delicate vocal",
      "Intimate vocal",
      "Hushed vocal",
      "Fragile vocal",
      "Lullaby vocal",
      "Floating vocal",
      "Velvet vocal",
      "Emotional vocal",
      "Soulful vocal",
      "Passionate vocal",
      "Heartfelt vocal",
      "Dramatic vocal",
      "Crying vocal",
      "Melancholic vocal",
      "Vulnerable vocal",
      "Powerful emotional vocal",
      "Yearning vocal",
      "Painful vocal",
      "Reflective vocal",
      "Longing vocal",
      "Raw vocal",
      "Confessional vocal",
      "Powerful vocal",
      "Belting vocal",
      "Big voice vocal",
      "Anthem vocal",
      "Commanding vocal",
      "Operatic vocal",
      "Dynamic vocal",
      "Full voice vocal",
      "Thunderous vocal",
      "Heroic vocal",
      "Dramatic belt",
      "Strong vibrato vocal",
      "Arena vocal",
      "Epic vocal",
      "Intense vocal",
      "Rap vocal",
      "Fast rap",
      "Melodic rap",
      "Spoken word vocal",
      "Storytelling rap",
      "Aggressive rap",
      "Flow rap",
      "Smooth rap",
      "Chant vocal",
      "Crowd chant",
      "Hype vocal",
      "Trap rap vocal",
      "Drill rap vocal",
      "Half-sung rap",
      "Rhythmic vocal",
      "Gospel vocal",
      "Blues vocal",
      "Jazz vocal",
      "Country vocal",
      "Indie vocal",
      "Folk vocal",
      "Pop vocal",
      "Rock vocal",
      "Punk vocal",
      "Metal vocal",
      "Raspy vocal",
      "Gritty vocal",
      "Shouting vocal",
      "Screaming vocal",
      "Growl vocal",
      "Distorted vocal",
      "Raw rock vocal",
      "Punk shout",
      "Hardcore vocal",
      "Snarling vocal",
      "Echo vocal",
      "Reverb-heavy vocal",
      "Layered vocal",
      "Choir vocal",
      "Harmonic vocal",
      "Ethereal vocal",
      "Ambient vocal",
      "Robotic vocal",
      "Vocoder vocal",
      "Auto-tuned vocal",
      "Falsetto vocal",
      "Yodel vocal",
      "Spoken narration",
      "Whisper rap",
      "Vocal fry style",
      "Chanting vocal",
      "Tribal vocal",
      "Call-and-response vocal",
      "Scat singing",
      "Experimental vocal",
    ],
  },
  {
    key: "concepts",
    label: "Concepts",
    enabled: true,
    items: [
      "theme: First Love",
      "theme: Heartbreak",
      "theme: Unrequited Love",
      "theme: Toxic Relationship",
      "theme: Falling in Love",
      "theme: Long Distance Love",
      "theme: Forbidden Love",
      "theme: Rekindled Romance",
      "theme: Secret Crush",
      "theme: Soulmates",
      "theme: Mental Health",
      "theme: Depression",
      "theme: Anxiety",
      "theme: Addiction",
      "theme: Self-Doubt",
      "theme: Loneliness",
      "theme: Burnout",
      "theme: Overcoming Trauma",
      "theme: Identity Crisis",
      "theme: Inner Conflict",
      "theme: Self-Discovery",
      "theme: Personal Growth",
      "theme: Redemption",
      "theme: Second Chances",
      "theme: Overcoming Obstacles",
      "theme: Chasing Dreams",
      "theme: Never Giving Up",
      "theme: Rising From Failure",
      "theme: Confidence",
      "theme: Becoming Your True Self",
      "theme: Coming of Age",
      "theme: Nostalgia",
      "theme: Childhood Memories",
      "theme: Growing Older",
      "theme: Moving On",
      "theme: Life Lessons",
      "theme: Small Town Life",
      "theme: City Life",
      "theme: Late Night Thoughts",
      "theme: New Beginnings",
      "theme: Road Trips",
      "theme: Travel",
      "theme: Exploring the World",
      "theme: Freedom",
      "theme: Escaping the Ordinary",
      "theme: Finding Your Path",
      "theme: Wandering",
      "theme: Adventure With Friends",
      "theme: Searching for Meaning",
      "theme: Discovery",
      "theme: Inequality",
      "theme: Corruption",
      "theme: Political Protest",
      "theme: Social Justice",
      "theme: War and Peace",
      "theme: Environmental Awareness",
      "theme: Cultural Identity",
      "theme: Media Influence",
      "theme: Consumerism",
      "theme: Freedom of Speech",
      "theme: Revenge",
      "theme: Betrayal",
      "theme: Power Struggles",
      "theme: Crime Life",
      "theme: Survival",
      "theme: Chaos",
      "theme: Inner Demons",
      "theme: Moral Conflict",
      "theme: Obsession",
      "theme: Loss",
      "theme: Mythical Creatures",
      "theme: Magic and Sorcery",
      "theme: Ancient Legends",
      "theme: Heroes vs Villains",
      "theme: Time Travel",
      "theme: Parallel Worlds",
      "theme: Destiny",
      "theme: Epic Quests",
      "theme: Lost Kingdoms",
      "theme: Cosmic Journeys",
      "theme: Celebration",
      "theme: Nightlife",
      "theme: Friendship",
      "theme: Summer Vibes",
      "theme: Festivals",
      "theme: Dancing All Night",
      "theme: Living in the Moment",
      "theme: Good Times",
      "theme: Youthful Freedom",
      "theme: Weekend Adventures",
      "theme: Faith",
      "theme: Spiritual Awakening",
      "theme: Hope",
      "theme: Gratitude",
      "theme: Inner Peace",
      "theme: Purpose in Life",
      "theme: Destiny vs Choice",
      "theme: Redemption Through Faith",
      "theme: Connection to Nature",
      "theme: Enlightenment",
      "emotion: Love",
      "emotion: Passion",
      "emotion: Desire",
      "emotion: Infatuation",
      "emotion: Devotion",
      "emotion: Romance",
      "emotion: Longing",
      "emotion: Affection",
      "emotion: Lust",
      "emotion: Attraction",
      "emotion: Heartbreak",
      "emotion: Sadness",
      "emotion: Grief",
      "emotion: Loneliness",
      "emotion: Betrayal",
      "emotion: Regret",
      "emotion: Abandonment",
      "emotion: Sorrow",
      "emotion: Despair",
      "emotion: Emotional Pain",
      "emotion: Anger",
      "emotion: Rage",
      "emotion: Frustration",
      "emotion: Bitterness",
      "emotion: Hatred",
      "emotion: Revenge",
      "emotion: Jealousy",
      "emotion: Envy",
      "emotion: Resentment",
      "emotion: Defiance",
      "emotion: Hopelessness",
      "emotion: Anxiety",
      "emotion: Fear",
      "emotion: Insecurity",
      "emotion: Doubt",
      "emotion: Stress",
      "emotion: Vulnerability",
      "emotion: Isolation",
      "emotion: Helplessness",
      "emotion: Exhaustion",
      "emotion: Determination",
      "emotion: Courage",
      "emotion: Confidence",
      "emotion: Ambition",
      "emotion: Empowerment",
      "emotion: Pride",
      "emotion: Resilience",
      "emotion: Hope",
      "emotion: Triumph",
      "emotion: Drive",
      "emotion: Nostalgia",
      "emotion: Melancholy",
      "emotion: Reflection",
      "emotion: Contemplation",
      "emotion: Soul Searching",
      "emotion: Acceptance",
      "emotion: Forgiveness",
      "emotion: Healing",
      "emotion: Inner Peace",
      "emotion: Self Awareness",
      "emotion: Happiness",
      "emotion: Joy",
      "emotion: Excitement",
      "emotion: Celebration",
      "emotion: Freedom",
      "emotion: Gratitude",
      "emotion: Bliss",
      "emotion: Contentment",
      "emotion: Satisfaction",
      "emotion: Optimism",
      "emotion: Curiosity",
      "emotion: Wonder",
      "emotion: Fascination",
      "emotion: Suspense",
      "emotion: Anticipation",
      "emotion: Awe",
      "emotion: Amazement",
      "emotion: Intrigue",
      "emotion: Surprise",
      "emotion: Mystery",
      "emotion: Obsession",
      "emotion: Madness",
      "emotion: Guilt",
      "emotion: Shame",
      "emotion: Paranoia",
      "emotion: Desperation",
      "emotion: Corruption",
      "emotion: Temptation",
      "emotion: Chaos",
      "emotion: Inner Darkness",
      "emotion: Friendship",
      "emotion: Loyalty",
      "emotion: Trust",
      "emotion: Compassion",
      "emotion: Empathy",
      "emotion: Belonging",
      "emotion: Support",
      "emotion: Unity",
      "emotion: Admiration",
      "emotion: Respect",
      "subject: Wedding Ring",
      "subject: Broken Heart",
      "subject: Love Letter",
      "subject: Locket",
      "subject: Rose",
      "subject: Wilted Rose",
      "subject: Red Ribbon",
      "subject: Photograph",
      "subject: Two Chairs",
      "subject: Shared Umbrella",
      "subject: Heart Locket",
      "subject: Old Valentine",
      "subject: Perfume Bottle",
      "subject: Music Box",
      "subject: Engagement Ring",
      "subject: Couple’s Necklace",
      "subject: Love Note",
      "subject: Bouquet",
      "subject: Anniversary Gift",
      "subject: Wedding Veil",
      "subject: Glass of Wine",
      "subject: Candlelight",
      "subject: Couple’s Bench",
      "subject: Handwritten Poem",
      "subject: Love Song Record",
      "subject: Picture Frame",
      "subject: Lock & Key",
      "subject: Heart Pendant",
      "subject: Couple’s Bracelet",
      "subject: Shared Blanket",
      "subject: Romantic Candle",
      "subject: Love Diary",
      "subject: Engagement Photo",
      "subject: Wedding Invitation",
      "subject: Love Charm",
      "subject: Promise Ring",
      "subject: Wedding Cake",
      "subject: Rose Petals",
      "subject: Romantic Candle Flame",
      "subject: Love Token",
      "subject: Clock",
      "subject: Hourglass",
      "subject: Pocket Watch",
      "subject: Old Photograph",
      "subject: Photo Album",
      "subject: Diary",
      "subject: Journal",
      "subject: Faded Letter",
      "subject: Scrapbook",
      "subject: Candle",
      "subject: Sand Timer",
      "subject: Calendar Page",
      "subject: Time Capsule",
      "subject: Memory Box",
      "subject: Old Cassette",
      "subject: Vinyl Record",
      "subject: Childhood Toy",
      "subject: Ticket Stub",
      "subject: Newspaper Clipping",
      "subject: Antique Watch",
      "subject: Sundial",
      "subject: Old Film Reel",
      "subject: Tape Recorder",
      "subject: Burned Photograph",
      "subject: Dusty Book",
      "subject: Old Key",
      "subject: Antique Mirror",
      "subject: Rusty Clock",
      "subject: Forgotten Notebook",
      "subject: Music Record Sleeve",
      "subject: Photo Negative",
      "subject: Pressed Flower",
      "subject: Old Coin",
      "subject: Timepiece",
      "subject: Family Heirloom",
      "subject: Baby Shoes",
      "subject: Old Postcard",
      "subject: Memory Jar",
      "subject: Burned Candle",
      "subject: Aging Tree",
      "subject: Road",
      "subject: Crossroads",
      "subject: Compass",
      "subject: Map",
      "subject: Train Ticket",
      "subject: Suitcase",
      "subject: Footprints",
      "subject: Bridge",
      "subject: Open Gate",
      "subject: Lighthouse",
      "subject: Trail Marker",
      "subject: Pathway",
      "subject: Highway Sign",
      "subject: Backpack",
      "subject: Hiking Boots",
      "subject: Travel Journal",
      "subject: Passport",
      "subject: Train Station",
      "subject: Harbor Dock",
      "subject: Sailing Ship",
      "subject: River Crossing",
      "subject: Dirt Road",
      "subject: City Street",
      "subject: Desert Trail",
      "subject: Tunnel",
      "subject: Mountain Pass",
      "subject: Staircase",
      "subject: Doorway",
      "subject: Open Window",
      "subject: Departure Board",
      "subject: Boarding Pass",
      "subject: Lantern",
      "subject: Streetlamp",
      "subject: Ferry Boat",
      "subject: Car Keys",
      "subject: Bus Stop",
      "subject: Train Tracks",
      "subject: Compass Rose",
      "subject: Milestone Marker",
      "subject: Guiding Star",
      "subject: Star",
      "subject: Shooting Star",
      "subject: Sunrise",
      "subject: Lantern",
      "subject: Paper Airplane",
      "subject: Key",
      "subject: Open Door",
      "subject: Feather",
      "subject: Balloon",
      "subject: Wings",
      "subject: Rainbow",
      "subject: Spark",
      "subject: Firework",
      "subject: Candle Flame",
      "subject: Rising Sun",
      "subject: Light Beam",
      "subject: Dreamcatcher",
      "subject: Silver Lining",
      "subject: Shooting Comet",
      "subject: Floating Lantern",
      "subject: Wishbone",
      "subject: Wish Lantern",
      "subject: Guiding Light",
      "subject: Golden Key",
      "subject: Shooting Light",
      "subject: Lucky Coin",
      "subject: Clover",
      "subject: Seedling",
      "subject: Blooming Flower",
      "subject: Butterfly",
      "subject: Eagle Feather",
      "subject: Rising Kite",
      "subject: Golden Path",
      "subject: North Star",
      "subject: Glowing Orb",
      "subject: Sunbeam",
      "subject: Dream Journal",
      "subject: Open Sky",
      "subject: Bright Horizon",
      "subject: Morning Dew",
      "subject: Wilted Flower",
      "subject: Empty Chair",
      "subject: Broken Mirror",
      "subject: Fallen Leaf",
      "subject: Rain Window",
      "subject: Extinguished Candle",
      "subject: Abandoned House",
      "subject: Torn Photograph",
      "subject: Shadow",
      "subject: Echo",
      "subject: Cracked Glass",
      "subject: Broken Necklace",
      "subject: Rusty Gate",
      "subject: Forgotten Grave",
      "subject: Burned Letter",
      "subject: Dark Cloud",
      "subject: Withered Tree",
      "subject: Collapsed Bridge",
      "subject: Empty Room",
      "subject: Silent Piano",
      "subject: Abandoned Toy",
      "subject: Cold Fireplace",
      "subject: Lonely Road",
      "subject: Dark Alley",
      "subject: Flickering Light",
      "subject: Closed Door",
      "subject: Lost Key",
      "subject: Broken Clock",
      "subject: Fallen Statue",
      "subject: Deserted Street",
      "subject: Empty Theater",
      "subject: Dead Rose",
      "subject: Empty Frame",
      "subject: Cracked Wall",
      "subject: Dusty Window",
      "subject: Torn Diary",
      "subject: Ashes",
      "subject: Black Feather",
      "subject: Shattered Glass",
      "subject: Silent Bell",
      "subject: Crown",
      "subject: Throne",
      "subject: Sword",
      "subject: Shield",
      "subject: Coin",
      "subject: Dice",
      "subject: Mask",
      "subject: Chain",
      "subject: Lock",
      "subject: Keyhole",
      "subject: Royal Ring",
      "subject: Golden Crown",
      "subject: Scepter",
      "subject: Royal Seal",
      "subject: Banner",
      "subject: Flag",
      "subject: Torch",
      "subject: Medal",
      "subject: Armor",
      "subject: Helmet",
      "subject: Staff",
      "subject: Totem",
      "subject: Tribal Mark",
      "subject: Crest",
      "subject: Power Stone",
      "subject: Sacred Relic",
      "subject: Throne Room",
      "subject: Battle Standard",
      "subject: Victory Laurel",
      "subject: Champion Belt",
      "subject: Mirror",
      "subject: Mask",
      "subject: Shadow",
      "subject: Hidden Door",
      "subject: Puzzle Piece",
      "subject: Secret Box",
      "subject: Labyrinth",
      "subject: Fog",
      "subject: Veil",
      "subject: Whisper",
      "subject: Hidden Key",
      "subject: Secret Letter",
      "subject: Locked Chest",
      "subject: Dark Corridor",
      "subject: Hidden Passage",
      "subject: Secret Map",
      "subject: Cloak",
      "subject: Hood",
      "subject: Crystal Ball",
      "subject: Tarot Card",
      "subject: Oracle Stone",
      "subject: Puzzle Lock",
      "subject: Hidden Symbol",
      "subject: Masked Face",
      "subject: Shadow Figure",
      "subject: Secret Code",
      "subject: Invisible Ink",
      "subject: Ancient Scroll",
      "subject: Magic Mirror",
      "subject: Mysterious Door",
      "subject: Tree",
      "subject: River",
      "subject: Ocean",
      "subject: Storm",
      "subject: Mountain",
      "subject: Moon",
      "subject: Sun",
      "subject: Fire",
      "subject: Ice",
      "subject: Wind",
      "subject: Waterfall",
      "subject: Thunder",
      "subject: Lightning",
      "subject: Snowflake",
      "subject: Volcano",
      "subject: Desert",
      "subject: Sand Dune",
      "subject: Rainstorm",
      "subject: Cloud",
      "subject: Valley",
      "subject: Forest",
      "subject: Meadow",
      "subject: Canyon",
      "subject: Cliff",
      "subject: Tidal Wave",
      "subject: Aurora",
      "subject: Glacier",
      "subject: Earthquake",
      "subject: Starry Sky",
      "subject: Wildfire",
      "subject: Memory",
      "subject: Dream",
      "subject: Silence",
      "subject: Light",
      "subject: Darkness",
      "subject: Time",
      "subject: Destiny",
      "subject: Infinity",
      "subject: Reflection",
      "subject: Fate",
      "action: Falling in love",
      "action: Confessing feelings",
      "action: Holding hands",
      "action: Kissing",
      "action: Missing someone",
      "action: Waiting for someone",
      "action: Chasing love",
      "action: Flirting",
      "action: Rekindling romance",
      "action: Saying goodbye",
      "action: Breaking up",
      "action: Forgiving someone",
      "action: Reuniting",
      "action: Writing a love letter",
      "action: Calling late at night",
      "action: Dancing together",
      "action: Running away together",
      "action: Fighting in a relationship",
      "action: Making up",
      "action: Proposing",
      "action: Promising forever",
      "action: Letting go of love",
      "action: Remembering an ex",
      "action: Falling out of love",
      "action: Secretly loving someone",
      "action: Protecting someone",
      "action: Comforting someone",
      "action: Longing for someone",
      "action: Admiring from afar",
      "action: Sharing a moment",
      "action: Arguing",
      "action: Apologizing",
      "action: Betraying someone",
      "action: Trusting someone",
      "action: Losing trust",
      "action: Supporting someone",
      "action: Walking away",
      "action: Holding on",
      "action: Starting over together",
      "action: Loving from a distance",
      "action: Finding yourself",
      "action: Chasing dreams",
      "action: Overcoming fear",
      "action: Standing up for yourself",
      "action: Learning from mistakes",
      "action: Starting over",
      "action: Rising after failure",
      "action: Taking a risk",
      "action: Following your heart",
      "action: Breaking free",
      "action: Growing stronger",
      "action: Facing your past",
      "action: Discovering purpose",
      "action: Making a change",
      "action: Rebuilding life",
      "action: Letting go of the past",
      "action: Taking control",
      "action: Fighting for your future",
      "action: Becoming who you are",
      "action: Moving forward",
      "action: Accepting yourself",
      "action: Learning to forgive",
      "action: Finding hope",
      "action: Standing alone",
      "action: Finding inner peace",
      "action: Conquering doubt",
      "action: Taking the leap",
      "action: Believing in yourself",
      "action: Learning to trust",
      "action: Building confidence",
      "action: Healing wounds",
      "action: Searching for meaning",
      "action: Embracing change",
      "action: Walking your own path",
      "action: Standing your ground",
      "action: Surviving hardship",
      "action: Rising above hate",
      "action: Transforming your life",
      "action: Facing the truth",
      "action: Claiming victory",
      "action: Fighting back",
      "action: Seeking revenge",
      "action: Breaking chains",
      "action: Escaping danger",
      "action: Surviving chaos",
      "action: Standing against power",
      "action: Rebelling",
      "action: Challenging authority",
      "action: Confronting enemies",
      "action: Battling inner demons",
      "action: Fighting injustice",
      "action: Defending someone",
      "action: Running from the past",
      "action: Seeking justice",
      "action: Breaking rules",
      "action: Burning bridges",
      "action: Walking away from lies",
      "action: Hiding secrets",
      "action: Exposing the truth",
      "action: Taking revenge",
      "action: Starting a revolution",
      "action: Defying fate",
      "action: Surviving the storm",
      "action: Climbing out of darkness",
      "action: Resisting temptation",
      "action: Fighting addiction",
      "action: Breaking bad habits",
      "action: Escaping oppression",
      "action: Surviving betrayal",
      "action: Destroying illusions",
      "action: Traveling the world",
      "action: Driving through the night",
      "action: Running away",
      "action: Exploring new places",
      "action: Chasing the horizon",
      "action: Wandering",
      "action: Sailing away",
      "action: Climbing mountains",
      "action: Crossing oceans",
      "action: Searching for treasure",
      "action: Escaping the city",
      "action: Taking a road trip",
      "action: Following the stars",
      "action: Discovering new lands",
      "action: Walking unknown paths",
      "action: Riding into the sunset",
      "action: Racing against time",
      "action: Crossing borders",
      "action: Flying away",
      "action: Venturing into the unknown",
      "action: Chasing adventure",
      "action: Finding hidden places",
      "action: Drifting through life",
      "action: Journeying home",
      "action: Hiking through wilderness",
      "action: Following a map",
      "action: Finding your way",
      "action: Returning home",
      "action: Leaving everything behind",
      "action: Starting a journey",
      "action: Remembering the past",
      "action: Looking back",
      "action: Reflecting on life",
      "action: Dreaming of the future",
      "action: Missing someone",
      "action: Reliving memories",
      "action: Letting emotions out",
      "action: Crying alone",
      "action: Watching the rain",
      "action: Sitting in silence",
      "action: Writing in a diary",
      "action: Praying for answers",
      "action: Wondering what could have been",
      "action: Searching your soul",
      "action: Thinking about someone",
      "action: Looking at old photos",
      "action: Listening to old songs",
      "action: Feeling nostalgia",
      "action: Contemplating life",
      "action: Accepting reality",
      "action: Forgiving yourself",
      "action: Finding peace",
      "action: Releasing pain",
      "action: Closing a chapter",
      "action: Opening your heart",
      "action: Healing slowly",
      "action: Making peace with the past",
      "action: Facing regrets",
      "action: Learning from heartbreak",
      "action: Moving on",
      "action: Celebrating life",
      "action: Dancing all night",
      "action: Laughing with friends",
      "action: Living in the moment",
      "action: Throwing a party",
      "action: Singing loudly",
      "action: Embracing freedom",
      "action: Enjoying summer",
      "action: Watching the sunset",
      "action: Toasting success",
      "action: Winning the fight",
      "action: Achieving dreams",
      "action: Feeling unstoppable",
      "action: Spreading joy",
      "action: Making memories",
      "action: Sharing happiness",
      "action: Running wild",
      "action: Playing in the rain",
      "action: Living carefree",
      "action: Celebrating victory",
      "action: Making new friends",
      "action: Embracing the night",
      "action: Finding joy in chaos",
      "action: Dancing in the streets",
      "action: Laughing at life",
      "action: Enjoying the ride",
      "action: Feeling alive",
      "action: Making the most of today",
      "action: Creating moments",
      "action: Living your dream",
      "target: Mother",
      "target: Father",
      "target: Brother",
      "target: Sister",
      "target: Grandmother",
      "target: Grandfather",
      "target: Daughter",
      "target: Son",
      "target: Lover",
      "target: Ex Lover",
      "target: Best Friend",
      "target: Childhood Friend",
      "target: Stranger",
      "target: Neighbor",
      "target: Roommate",
      "target: Husband",
      "target: Wife",
      "target: Partner",
      "target: Bride",
      "target: Groom",
      "target: Cousin",
      "target: Uncle",
      "target: Aunt",
      "target: Mentor",
      "target: Rival",
      "target: Enemy",
      "target: Hero",
      "target: Protector",
      "target: Guardian",
      "target: Caregiver",
      "target: Teacher",
      "target: Student",
      "target: Classmate",
      "target: Babysitter",
      "target: Foster Parent",
      "target: Stepbrother",
      "target: Stepsister",
      "target: Childhood Crush",
      "target: Lost Friend",
      "target: Soulmate",
      "target: Musician",
      "target: Singer",
      "target: DJ",
      "target: Producer",
      "target: Painter",
      "target: Poet",
      "target: Writer",
      "target: Actor",
      "target: Comedian",
      "target: Director",
      "target: Doctor",
      "target: Nurse",
      "target: Surgeon",
      "target: Firefighter",
      "target: Police Officer",
      "target: Detective",
      "target: Soldier",
      "target: Captain",
      "target: Pilot",
      "target: Astronaut",
      "target: Scientist",
      "target: Engineer",
      "target: Mechanic",
      "target: Farmer",
      "target: Fisherman",
      "target: Chef",
      "target: Baker",
      "target: Bartender",
      "target: Waiter",
      "target: Taxi Driver",
      "target: Truck Driver",
      "target: Bus Driver",
      "target: Train Conductor",
      "target: Sailor",
      "target: Explorer",
      "target: Archaeologist",
      "target: Photographer",
      "target: Journalist",
      "target: Reporter",
      "target: News Anchor",
      "target: Librarian",
      "target: Professor",
      "target: Coach",
      "target: Athlete",
      "target: Boxer",
      "target: Dancer",
      "target: Fashion Designer",
      "target: Architect",
      "target: Builder",
      "target: Inventor",
      "target: King",
      "target: Queen",
      "target: Prince",
      "target: Princess",
      "target: Knight",
      "target: Warrior",
      "target: Samurai",
      "target: Viking",
      "target: Pirate",
      "target: Captain",
      "target: Hero",
      "target: Villain",
      "target: Rebel",
      "target: Outlaw",
      "target: Wanderer",
      "target: Nomad",
      "target: Traveler",
      "target: Explorer",
      "target: Guardian",
      "target: Messenger",
      "target: Prophet",
      "target: Oracle",
      "target: Wizard",
      "target: Sorcerer",
      "target: Witch",
      "target: Healer",
      "target: Seer",
      "target: Mystic",
      "target: Trickster",
      "target: Dreamer",
      "target: Survivor",
      "target: Champion",
      "target: Leader",
      "target: Ruler",
      "target: Protector",
      "target: Shepherd",
      "target: Hunter",
      "target: Scout",
      "target: Pioneer",
      "target: Adventurer",
      "target: Gladiator",
      "target: Legend",
      "target: Champion Fighter",
      "target: Lost Soul",
      "target: Chosen One",
      "target: Fallen Hero",
      "target: Lone Ranger",
      "target: Silent Stranger",
      "target: Midnight Rider",
      "target: Shadow Walker",
      "target: City Street",
      "target: Alleyway",
      "target: Rooftop",
      "target: Subway Station",
      "target: Train Station",
      "target: Bus Stop",
      "target: Airport",
      "target: Downtown",
      "target: Skyscraper",
      "target: Apartment",
      "target: Hotel Room",
      "target: Motel",
      "target: Bar",
      "target: Nightclub",
      "target: Restaurant",
      "target: Café",
      "target: Coffee Shop",
      "target: Bookstore",
      "target: Record Store",
      "target: Movie Theater",
      "target: Stadium",
      "target: Concert Hall",
      "target: Studio",
      "target: Garage",
      "target: Parking Lot",
      "target: City Park",
      "target: Bridge",
      "target: Highway",
      "target: Gas Station",
      "target: Mall",
      "target: Tattoo Shop",
      "target: Barber Shop",
      "target: Corner Store",
      "target: Police Station",
      "target: Hospital",
      "target: Fire Station",
      "target: Courthouse",
      "target: Office Building",
      "target: Factory",
      "target: Warehouse",
      "target: Forest",
      "target: Jungle",
      "target: Mountain",
      "target: Valley",
      "target: River",
      "target: Lake",
      "target: Ocean",
      "target: Beach",
      "target: Desert",
      "target: Canyon",
      "target: Waterfall",
      "target: Cliff",
      "target: Cave",
      "target: Meadow",
      "target: Field",
      "target: Orchard",
      "target: Vineyard",
      "target: Swamp",
      "target: Glacier",
      "target: Island",
      "target: Volcano",
      "target: Tundra",
      "target: Prairie",
      "target: Oasis",
      "target: Rainforest",
      "target: Snowy Mountain",
      "target: Frozen Lake",
      "target: Coral Reef",
      "target: Sand Dunes",
      "target: Coastal Cliff",
      "target: Wild Plains",
      "target: Hidden Valley",
      "target: Deep Woods",
      "target: Starry Sky",
      "target: Northern Lights",
      "target: Stormy Sea",
      "target: Open Horizon",
      "target: Sunset Beach",
      "target: Midnight Desert",
      "target: Sunrise Hill",
      "target: Castle",
      "target: Kingdom",
      "target: Throne Room",
      "target: Battlefield",
      "target: Dungeon",
      "target: Temple",
      "target: Shrine",
      "target: Ancient Ruins",
      "target: Hidden Village",
      "target: Secret Garden",
      "target: Magic Forest",
      "target: Crystal Cave",
      "target: Floating City",
      "target: Lost City",
      "target: Sacred Mountain",
      "target: Pirate Cove",
      "target: Treasure Island",
      "target: Forgotten Temple",
      "target: Haunted House",
      "target: Ghost Town",
      "target: Space Station",
      "target: Alien Planet",
      "target: Galactic Empire",
      "target: Starship",
      "target: Time Portal",
      "target: Dream World",
      "target: Parallel Universe",
      "target: Underwater City",
      "target: Ancient Library",
      "target: Secret Laboratory",
      "target: Dark Fortress",
      "target: Forbidden Land",
      "target: Royal Palace",
      "target: Hidden Fortress",
      "target: Mystic Tower",
      "target: Shadow Realm",
      "target: Cosmic Gate",
      "target: Celestial City",
      "target: Eternal Garden",
      "target: Golden Kingdom",
      "target: The Dreamer",
      "target: The Wanderer",
      "target: The Outsider",
      "target: The Believer",
      "target: The Fighter",
      "target: The Survivor",
      "target: The Rebel",
      "target: The Broken One",
      "target: The Lost One",
      "target: The Chosen One",
      "target: The Guardian",
      "target: The Stranger",
      "target: The Messenger",
      "target: The Healer",
      "target: The Visionary",
      "target: The Seeker",
      "target: The Teacher",
      "target: The Leader",
      "target: The Protector",
      "target: The Creator",
      "target: The Destroyer",
      "target: The Witness",
      "target: The Listener",
      "target: The Silent One",
      "target: The Night Walker",
      "target: The Storm Bringer",
      "target: The Light Bearer",
      "target: The Shadow King",
      "target: The Last Survivor",
      "target: The Forgotten Hero",
      "target: The Lone Rider",
      "target: The Time Traveler",
      "target: The Gatekeeper",
      "target: The Storyteller",
      "target: The Pathfinder",
      "target: The Trailblazer",
      "target: The Star Chaser",
      "target: The Flame Keeper",
      "target: The Truth Seeker",
      "target: The Peacekeeper",
    ],
  },
  {
    key: "reference",
    label: "Reference",
    enabled: false,
    items: referenceItems,
  },
];
