export const referenceItems: string[] = [
  "Driving alone at night",
  "Waiting at a bus stop in the rain",
  "A quiet Sunday morning",
  "A late-night diner conversation",
  "Walking home after a long shift",
  "Grocery shopping while emotionally wrecked",
  "A first date that goes surprisingly well",
  "Missing the last train home",
  "Watching the sunrise after staying up all night",
  "Cleaning your room after a breakup",
  "A small-town Friday night",
  "Riding through the city in the back seat",
  "Waiting for someone who never arrives",
  "A long drive with no destination",
  "Sitting in a parked car thinking",
  "A slow afternoon in a coffee shop",
  "Running into someone from your past",
  "Folding laundry while daydreaming",
  "A lonely motel stop on the highway",
  "Calling someone you should not call",
  "Staring out the window on a plane",
  "Watching neighbors through apartment windows",
  "Walking through a grocery store at midnight",
  "Missing home in a new city",
  "A packed subway ride in silence",
  "Watching rain hit the windshield",
  "Going back to your hometown",
  "Getting ready for a night out",
  "A long elevator ride after bad news",
  "Standing in line at an airport",
  "Driving with the windows down in summer",
  "A quiet evening on the porch",
  "A beach bonfire with friends",
  "Hearing a song that ruins your day",
  "Going nowhere on purpose",
  "A night walk through your neighborhood",
  "Sitting in traffic with too much on your mind",
  "Leaving a party early",
  "A rooftop hangout after midnight",
  "Watching a thunderstorm roll in",
  "Sleeping on a friend’s couch",
  "The train leaving without you",
  "A road trip gas station stop",
  "Making coffee before sunrise",
  "A lonely hotel room",
  "Missing someone in a crowded room",
  "Walking through an empty parking lot",
  "Going home after a funeral",
  "A long checkout line and a longer day",
  "The ride back after everything changes",
  "Falling for someone too fast",
  "A first kiss under streetlights",
  "Wanting somebody unavailable",
  "Loving someone from a distance",
  "A breakup text at 2AM",
  "Running into your ex in public",
  "Watching someone fall out of love",
  "Reuniting after years apart",
  "Saying goodbye at the airport",
  "A love that almost happened",
  "Being someone’s second choice",
  "Learning to love yourself again",
  "Secretly wanting your best friend",
  "Wanting closure you never get",
  "Dancing with someone you should avoid",
  "Missing how things used to feel",
  "A relationship ending in silence",
  "The night before a wedding",
  "Cheating and regretting it",
  "Knowing it is over before they do",
  "A one-night connection that lingers",
  "Falling back into old patterns",
  "Loving someone who cannot stay",
  "A long-distance phone call",
  "Begging someone not to leave",
  "Finally letting go",
  "A soulmate that arrived at the wrong time",
  "The awkwardness after a fight",
  "A love triangle nobody wins",
  "Choosing yourself instead",
  "A second chance romance",
  "A relationship built on nostalgia",
  "Meeting someone after heartbreak",
  "Watching them move on",
  "The moment you realize you were used",
  "Wanting someone who never really saw you",
  "A perfect date with terrible timing",
  "A wedding you should not attend",
  "Falling in love while healing",
  "Pretending you are over it",
  "The last night before a breakup",
  "A goodbye you replay forever",
  "Fighting for something already gone",
  "Loving someone who keeps disappearing",
  "Becoming strangers again",
  "A love story told in memories",
  "Being haunted by an old relationship",
  "Finally hearing the truth",
  "Forgiving without forgetting",
  "Choosing peace over passion",
  "A childhood friend you drifted from",
  "Brothers fighting then making peace",
  "A mother trying her best",
  "Growing up too fast",
  "Siblings against the world",
  "A family reunion with old tension",
  "Missing your grandparents",
  "The friend who always stayed",
  "The friend who betrayed you",
  "Laughing until sunrise with your people",
  "Protecting someone younger than you",
  "Calling your parents after good news",
  "A father who never says enough",
  "The last conversation with someone older",
  "Friends becoming strangers",
  "A chosen family moment",
  "Late-night talks with your best friend",
  "A friendship breakup",
  "Learning your parents were human too",
  "A cousin who feels like a sibling",
  "Losing touch with everyone at once",
  "The group chat after a major life change",
  "A family dinner hiding tension",
  "A mentor changing your life",
  "An older sibling carrying too much",
  "The friend who knew you before success",
  "Helping someone through a dark time",
  "A goodbye between best friends",
  "A sibling leaving home",
  "Three generations in one room",
  "Growing apart from hometown friends",
  "Carrying family expectations",
  "A friend covering for you",
  "A kid looking up to you",
  "The silence after an argument",
  "A friendship built on survival",
  "A teammate becoming family",
  "A friendship during summer break",
  "A grandmother’s kitchen",
  "A grandfather’s old stories",
  "The cousin who always gets it",
  "Family secrets surfacing",
  "Protecting your people at all costs",
  "A reunion nobody expected",
  "Becoming the strong one for everybody",
  "Missing a family member during the holidays",
  "A friend moving away",
  "Sharing one last laugh before goodbye",
  "The person who believed in you first",
  "Finding home in other people",
  "Reinventing yourself",
  "Starting over from nothing",
  "Finally saying no",
  "Outgrowing who you used to be",
  "Healing without closure",
  "Learning to trust yourself",
  "Becoming comfortable alone",
  "Facing your reflection honestly",
  "Letting go of old versions of you",
  "Choosing discipline over chaos",
  "Rebuilding after burnout",
  "Discovering what matters",
  "Becoming someone younger you needed",
  "Failing publicly and surviving",
  "Walking away from self-destruction",
  "Learning to breathe again",
  "The quiet power of self-respect",
  "A comeback nobody saw coming",
  "Reclaiming your voice",
  "Breaking your own cycle",
  "Turning pain into purpose",
  "Realizing you are not behind",
  "Learning how to rest",
  "Finally asking for help",
  "Becoming harder to manipulate",
  "Standing on your own two feet",
  "Choosing peace over proving a point",
  "Learning to live in the present",
  "Growing through loneliness",
  "Building confidence from scratch",
  "Shedding old shame",
  "Accepting uncertainty",
  "Becoming emotionally honest",
  "Starting life over in a new city",
  "Learning to forgive yourself",
  "Refusing to shrink yourself",
  "Becoming brave in small ways",
  "Discovering your own taste",
  "Fighting imposter syndrome",
  "Giving up the need to be liked",
  "Making yourself proud",
  "Becoming softer without becoming weak",
  "Learning to receive love",
  "Breaking free from old labels",
  "Becoming more than your past",
  "Realizing you deserve better",
  "The first day of your new life",
  "Walking into who you are",
  "Living without apology",
  "Making peace with your own name",
  "Coming up from nothing",
  "Late nights chasing a dream",
  "First big paycheck energy",
  "Building an empire from your room",
  "Becoming rich enough to breathe",
  "Grinding while everyone sleeps",
  "Your first sold-out show",
  "The pressure after success",
  "Wanting more after you win",
  "Looking successful but feeling empty",
  "Turning talent into a career",
  "Hating your job while building your future",
  "Counting every dollar",
  "Making it out of your hometown",
  "Luxury after years of struggle",
  "Quiet millionaire energy",
  "Winning out of spite",
  "Chasing a bigger life",
  "The loneliness of ambition",
  "Going all in on yourself",
  "Breaking into the industry",
  "Signing the deal",
  "Escaping survival mode",
  "Proving everyone wrong",
  "Working through exhaustion",
  "Fame before emotional maturity",
  "Watching your name rise",
  "Money changing relationships",
  "Living a life you once imagined",
  "The thrill of getting chosen",
  "Success that costs too much",
  "Building while doubting yourself",
  "Flexing because you survived",
  "Becoming the one people call now",
  "Rich but still restless",
  "Career high with a personal low",
  "Getting everything you asked for",
  "Becoming harder to impress",
  "Turning your pain into product",
  "Staying hungry after success",
  "Climbing with no elevator",
  "A city full of competition",
  "First-class after years of bus rides",
  "Spending money like it heals",
  "Hitting the chart for the first time",
  "Making art under pressure",
  "Becoming unforgettable",
  "The cost of being number one",
  "Legacy over clout",
  "Turning the dream into a system",
  "Saturday morning cartoons",
  "A 90s sitcom intro",
  "End credits of a teen movie",
  "A superhero training montage",
  "A reality show meltdown",
  "A red carpet entrance",
  "A movie trailer final shot",
  "An award show performance",
  "A paparazzi flashbulb moment",
  "A rom-com airport run",
  "A soap opera betrayal",
  "A late-night talk show walk-on",
  "A streaming-era cliffhanger ending",
  "A reality dating show elimination",
  "A boy band comeback special",
  "A girl group world-domination era",
  "A fashion week runway reveal",
  "A tabloid cover scandal",
  "A celebrity apology video",
  "A huge surprise album drop",
  "A blockbuster opening scene",
  "A cartoon villain entrance",
  "A sitcom final episode",
  "A teen drama hallway scene",
  "A cooking show timer counting down",
  "A makeover montage",
  "A dance competition final round",
  "A music documentary breakthrough scene",
  "A reality reunion special",
  "A fame spiral told through headlines",
  "A superhero mask-off moment",
  "A classic cartoon chase",
  "A reboot nobody asked for",
  "A streaming binge-watch weekend",
  "A rom-com in New York at Christmas",
  "A crowd screaming at a premiere",
  "A viral award show speech",
  "A franchise final battle feeling",
  "A school dance from a coming-of-age film",
  "A makeover scene in a mall",
  "A dramatic TV season finale",
  "A celebrity interview gone off-script",
  "A tabloid romance everyone follows",
  "A cult-classic movie ending",
  "A pre-credit action sequence",
  "A reality TV confession cam",
  "A music video iconic outfit moment",
  "A huge halftime performance",
  "A celebrity entering their flop era",
  "A star reclaiming the spotlight",
  "Saturday morning cartoon chaos",
  "A cartoon villain song",
  "A slapstick chase sequence",
  "A magical girl transformation",
  "An anime opening with too much emotion",
  "An anime ending theme after heartbreak",
  "A shonen training arc",
  "A final anime duel at sunset",
  "A slice-of-life school festival",
  "A cartoon hero discovering confidence",
  "A mascot dance number",
  "A bright-color adventure intro",
  "A villain redemption arc",
  "A giant robot launch sequence",
  "A beach episode feeling",
  "A tournament arc entrance",
  "A power-up moment with wind and sparks",
  "A friendship-saves-the-world finale",
  "A sad anime rain scene",
  "A cozy Ghibli-style train ride",
  "A comic relief side character theme",
  "A cartoon city at night",
  "A dramatic anime rooftop confession",
  "A transformation sequence with stars everywhere",
  "A heartfelt goodbye at the train platform",
  "A magical school hallway",
  "A cheerful end-credit dance",
  "A villain walking in slow motion",
  "A colorful monster-battle arena",
  "A childhood cartoon nostalgia rush",
  "An overpowered final form reveal",
  "A sports anime comeback point",
  "A cozy animation cooking scene",
  "A dreamy magical forest interlude",
  "A mecha battle launch countdown",
  "A chaotic cartoon parade",
  "A touching scene with no dialogue",
  "A dramatic anime rival entrance",
  "A villainess ballroom entrance",
  "A school rooftop lunch scene",
  "A fantasy-anime tavern celebration",
  "A city-pop anime night drive",
  "An emotional anime flashback montage",
  "A glitter-filled idol performance",
  "A chaotic cartoon chase through a mall",
  "A bittersweet animation finale",
  "A super-sentai team-up moment",
  "A rival duo staring each other down",
  "A whimsical animated dream sequence",
  "A childhood cartoon hero return",
  "A stream going viral overnight",
  "Hitting one million followers",
  "A live chat exploding",
  "A Discord call at 3AM",
  "A gaming tournament grand final",
  "A streamer rage-quit moment",
  "A speedrun world record",
  "A battle royale final circle",
  "An e-girl aesthetic livestream",
  "A meme spreading too far",
  "Doomscrolling after midnight",
  "A video essay existential spiral",
  "A gaming montage with impossible aim",
  "An old forum nostalgia trip",
  "A digital creator burnout arc",
  "Watching a server collapse in real time",
  "Internet drama nobody can escape",
  "A fan cam going hard",
  "A lo-fi study stream glow",
  "A late-night Minecraft build session",
  "A ranked match promotion game",
  "A creator posting through heartbreak",
  "A gaming café energy",
  "An online friendship becoming real",
  "A digital avatar living your truth",
  "A modded game universe",
  "First time going viral",
  "A speedrun reset after one mistake",
  "A YouTube rabbit hole at 2AM",
  "An internet subculture you found too late",
  "A headset on, world off kind of night",
  "A boss fight on one health",
  "A speedrun marathon finale",
  "A glowing PC setup in the dark",
  "A gaming lobby before the match starts",
  "The internet turning on a celebrity",
  "A cursed meme with too much power",
  "A digital friendship breakup",
  "A faceless creator reveal",
  "A montage of highlight clips",
  "A speedrunner shaking at the finish",
  "A fan edit made with heartbreak",
  "Going offline to save your mind",
  "A voice chat that feels like family",
  "The chaos of launch day",
  "A streamer crying after reaching the goal",
  "A gaming soundtrack final-level feel",
  "A LAN party throwback",
  "Logging off after life-changing news",
  "An internet era ending",
  "A roaring 20s speakeasy",
  "A 50s diner romance",
  "A 60s protest march",
  "A 70s disco floor",
  "A smoky 40s jazz club",
  "An 80s neon roller rink",
  "A 90s block party",
  "A Y2K mall glow",
  "A vinyl listening room in the 70s",
  "A wartime love letter",
  "A vintage train departure",
  "A black-and-white movie romance",
  "A western saloon showdown",
  "A 60s summer-of-love field",
  "A 70s funk street parade",
  "A 1920s ballroom",
  "A retro motel sign flickering",
  "A doo-wop street corner harmony",
  "A Woodstock field at golden hour",
  "A 90s after-school TV feeling",
  "A typewriter-and-cigarette noir room",
  "A retro radio broadcast night",
  "A wartime goodbye at the station",
  "A jazz age city nightlife",
  "A diner jukebox heartbreak",
  "A 1980s workout montage",
  "A 90s summer bike ride",
  "A cassette mixtape confession",
  "A classic Hollywood spotlight entrance",
  "A pinball arcade in 1987",
  "A drive-in movie romance",
  "A rollerskating date in 1979",
  "A 2000s pop princess era",
  "A grunge basement show in the 90s",
  "A 50s convertible summer cruise",
  "A vintage ballroom under chandeliers",
  "A neon motel by the highway",
  "A radio host spinning midnight soul",
  "A wartime city blackout",
  "A dance hall in old Havana",
  "A newspaper boy on city streets",
  "A moon landing generation dream",
  "A retro TV theme energy",
  "A city in 1930 during the rain",
  "A cassette player on the bus ride home",
  "A 70s soul club slow dance",
  "A postcard from another decade",
  "A polaroid summer in the early 2000s",
  "A history-book moment made personal",
  "A memory trapped in a different era",
  "A rainy New York midnight",
  "A Tokyo neon side street",
  "A Paris café in the rain",
  "A coastal drive in California",
  "A desert highway in Arizona",
  "A rooftop in Seoul at dusk",
  "A small-town Main Street",
  "A London alley after midnight",
  "A crowded market in Mexico City",
  "A summer night in Miami",
  "A tiny apartment in a huge city",
  "A train through the countryside",
  "A beach in late September",
  "A downtown skyline from far away",
  "A quiet mountain cabin",
  "A Mediterranean summer evening",
  "A gas station in the middle of nowhere",
  "A tropical resort after heartbreak",
  "A convenience store glow at 1AM",
  "A bustling airport terminal",
  "A motel on the interstate",
  "A city park at golden hour",
  "A snowy street under orange lights",
  "A hidden bookstore downtown",
  "A club district before midnight",
  "A rooftop overlooking endless lights",
  "A small town with one stoplight",
  "A carnival by the ocean",
  "A beach town in the off-season",
  "A long bridge over dark water",
  "A subway tunnel echo",
  "A remote cabin in winter",
  "A chaotic city square",
  "A sleepy coastal village",
  "An all-night gas station",
  "A countryside barn dance",
  "A parking garage after a concert",
  "A lakeside dock at sunset",
  "A neon-lit karaoke bar",
  "A boardwalk with old memories",
  "A theme park after closing",
  "A hostel in a city you do not know",
  "A station platform in cold weather",
  "A desert motel sign",
  "A skyline seen from the freeway",
  "A balcony in a foreign city",
  "A place that feels like escape",
  "A room that does not feel like home",
  "A road that leads nowhere and everywhere",
  "A city that raised you and broke you",
  "Y2K chrome aesthetic",
  "Soft girl bedroom glow",
  "Dark academia library mood",
  "Cottagecore in late summer",
  "Clean-girl morning routine energy",
  "Grunge poster-covered bedroom",
  "Vaporwave mall nostalgia",
  "Neon noir city haze",
  "Barbie pink confidence",
  "Indie sleaze nightlife",
  "Old-money elegance",
  "Maximalist fashion week chaos",
  "Minimal luxury apartment",
  "Tumblr-era soft sadness",
  "Glitter and heartbreak",
  "Film-camera summer memories",
  "Cloudy-day lo-fi bedroom",
  "Cyber aesthetic without the apocalypse",
  "Desert boho freedom",
  "High-fashion runway danger",
  "Romantic goth cathedral mood",
  "Retro-futurist chrome dreams",
  "Pastel arcade sweetness",
  "Dusty Americana road-movie look",
  "Luxury hotel lobby glamour",
  "Red lipstick and revenge",
  "Black leather and city lights",
  "Champagne and flash photography",
  "Soft-focus dream sequence",
  "Vintage postcard romance",
  "Gold-hour vacation glow",
  "Monochrome cool-girl confidence",
  "Cozy autumn bookstore energy",
  "Yacht-club summer privilege",
  "Club bathroom mirror confessions",
  "Floral chaos in spring",
  "All-black airport outfit power",
  "Icy silver futuristic elegance",
  "Messy eyeliner after midnight",
  "Velvet curtains and slow danger",
  "Designer shades and emotional distance",
  "Chrome hearts and heartbreak",
  "Rain on a neon sign",
  "Sunlight through sheer curtains",
  "Glitter after the party ends",
  "Streetwear and insomnia",
  "Satin sheets and bad decisions",
  "Luxury with loneliness underneath",
  "Expensive taste and emotional damage",
  "Moodboard energy turned into music",
  "A heart made of glass",
  "A storm inside your chest",
  "Running through fire to stay alive",
  "A lighthouse in a dark sea",
  "Building castles from broken pieces",
  "Chasing the horizon forever",
  "Dancing on the edge of disaster",
  "A house full of ghosts",
  "Wearing armor made of silence",
  "A wound that shines",
  "A flame that refuses to die",
  "A garden growing through concrete",
  "Carrying a city on your back",
  "Flying too close to the sun",
  "A mirror that tells the truth",
  "A wave that keeps returning",
  "Turning scars into constellations",
  "Standing in the eye of chaos",
  "A door that only opens inward",
  "A crown that feels too heavy",
  "A bridge burning behind you",
  "A train that never stops",
  "A room with no oxygen",
  "The sun breaking through storm clouds",
  "A paper boat in a flood",
  "A song trapped in your throat",
  "A clock with no mercy",
  "A city built on secrets",
  "Lighting a match in a hurricane",
  "Swimming through memory",
  "A river carrying the past",
  "A cracked halo",
  "A mountain made of doubt",
  "An anchor in open water",
  "A house of mirrors and lies",
  "Turning ashes into gold",
  "A voice in the static",
  "Falling upward",
  "A cage with the door unlocked",
  "A star refusing to burn out",
  "A garden of unfinished goodbyes",
  "A thunderstorm wearing lipstick",
  "An ocean in one tear",
  "A moon that never leaves",
  "A broken compass still pointing home",
  "A fire escape from your own mind",
  "A rose growing through ruins",
  "A knife hidden in velvet",
  "A flood after years of drought",
  "Walking barefoot through lightning",
  "The sound of freedom",
  "The cost of ambition",
  "The beginning of a new era",
  "The calm before collapse",
  "The rise of rebellion",
  "The beauty of imperfection",
  "Infinite possibility",
  "A world waking up",
  "The fear of the unknown",
  "Hope returning after years",
  "The pressure of expectation",
  "Time slipping away",
  "The weight of memory",
  "Reinvention as survival",
  "Desire versus peace",
  "The thrill of being chosen",
  "The loneliness of greatness",
  "The violence of change",
  "The elegance of restraint",
  "The intoxication of power",
  "Freedom that feels dangerous",
  "The hunger for meaning",
  "The collapse of certainty",
  "The afterglow of risk",
  "Softness as strength",
  "The end of denial",
  "The start of a movement",
  "Living without guarantees",
  "The shape of grief",
  "The seduction of chaos",
  "The truth behind the image",
  "A generation running hot",
  "The moment before history turns",
  "Beauty in the middle of ruin",
  "The ache of becoming",
  "The illusion of control",
  "The cost of being adored",
  "A future nobody prepared for",
  "The relief of honesty",
  "The burden of legacy",
  "Desire colliding with reality",
  "What survival sounds like",
  "When innocence breaks",
  "The moment after impact",
  "The sound of collective hope",
  "Ambition bigger than sleep",
  "When the mask comes off",
  "The courage to disappear",
  "The tension of almost",
  "A life split into before and after",
  "An anxiety spiral in public",
  "Crying in the bathroom at a party",
  "Feeling empty after good news",
  "Numbness after too much pain",
  "Smiling while falling apart",
  "Missing someone you should hate",
  "Relief after finally telling the truth",
  "Panic behind a calm face",
  "Confidence you had to fake first",
  "Jealousy you cannot admit",
  "Grief hitting late",
  "The shame of wanting attention",
  "Relief in walking away",
  "The guilt of success",
  "Loving someone and resenting them too",
  "Trying not to relapse into old habits",
  "Dissociation on a crowded street",
  "A quiet depressive morning",
  "The rage under politeness",
  "A hopeful night after months of darkness",
  "The weird calm after crying",
  "Wanting to disappear without dying",
  "Missing who you used to be",
  "Finally feeling safe",
  "Emotional whiplash after a breakup",
  "Laughing while your heart breaks",
  "The high of being desired",
  "The crash after the high",
  "Feeling replaced",
  "Feeling too much and saying too little",
  "A confidence surge before the show",
  "Fear disguised as arrogance",
  "Anger that comes from hurt",
  "The ache of nostalgia at midnight",
  "Looking okay but not being okay",
  "Realizing you are the problem too",
  "Feeling left behind by everyone",
  "Relief in being understood",
  "Wanting revenge but choosing peace",
  "The guilt after self-protection",
  "The loneliness of being needed by everyone",
  "Healing slower than you hoped",
  "The thrill of emotional danger",
  "A tiny moment of self-forgiveness",
  "The pressure to keep functioning",
  "Relief after survival",
  "Learning how to feel again",
  "The shock of being loved gently",
  "Peace after chaos",
  "Finally exhaling",
  "A band’s first garage rehearsal",
  "A singer alone with a piano",
  "A DJ before the drop",
  "A sold-out stadium opening moment",
  "A crowd chanting every word",
  "A guitar solo under bright white lights",
  "A producer finishing the perfect beat at dawn",
  "A songwriter finally finding the hook",
  "A late-night studio breakthrough",
  "A choir in a cathedral",
  "A jazz trio in a smoky room",
  "A rapper stepping into a cypher",
  "A battle of bands final round",
  "A house party performance",
  "A standing ovation after silence",
  "The encore everyone waits for",
  "A club DJ making the room erupt",
  "A raw acoustic set after midnight",
  "A singer losing it on the last chorus",
  "A festival crowd at sunset",
  "A rock band soundcheck in an arena",
  "A busker turning heads on the street",
  "A freestyle that changes a career",
  "A songwriter revising one line for hours",
  "A producer chasing the snare sound",
  "A concert encore in pouring rain",
  "A headline set at midnight",
  "A rehearsal room full of tension",
  "A dance crew final performance",
  "A vocalist doing one take that lasts forever",
  "A pop star entrance with pyrotechnics",
  "A crowd lifting phones in the air",
  "A band breaking up after the set",
  "A garage demo with magic in it",
  "A bedroom producer making something huge",
  "A string section entering at the perfect time",
  "An opera house full of breathless silence",
  "A punk basement show",
  "A freestyle session in the parking lot",
  "A recording booth confession",
  "The beat switch nobody expected",
  "The final note hanging in the room",
  "A producer alone with infinite revisions",
  "A rehearsal before the biggest show",
  "A singer hearing their own truth on playback",
  "A mic drop that actually earns it",
  "Music saving the night",
  "A crowd becoming one voice",
  "The song that writes itself",
  "A performance that changes everyone present",
  "A packed club at 1AM",
  "A rooftop party in summer",
  "Champagne spraying backstage",
  "A birthday night going off the rails",
  "A beach party under stars",
  "Dancing until the lights come on",
  "A warehouse rave in the city outskirts",
  "A prom night everything hinges on",
  "A wedding reception dance floor",
  "A house party with too many feelings",
  "A girls’ night out in matching outfits",
  "A VIP section with fake smiles",
  "The pregame before chaos",
  "A slow dance at closing time",
  "A downtown bar crawl",
  "Friends screaming the chorus together",
  "A summer festival after dark",
  "A pool party with hidden drama",
  "A karaoke night that gets emotional",
  "A club bathroom pep talk",
  "A college party that feels historic",
  "New Year’s Eve countdown tension",
  "A dance floor confession",
  "A post-concert afterparty",
  "Glitter on the floor the next morning",
  "Last call at the bar",
  "A packed room when the perfect song comes on",
  "Dancing in the kitchen with your friends",
  "A celebration after surviving a hard year",
  "A victory lap with your people",
  "A rooftop toast to a new chapter",
  "A city nightlife montage",
  "A lounge with velvet booths",
  "A hotel party on the top floor",
  "A reunion party with old feelings",
  "The chaos of everyone arriving at once",
  "A poolside luxury-nightlife feel",
  "A dance circle opening up",
  "A DJ set that saves the night",
  "Friends dressed like they mean it",
  "A champagne-fueled breakdown",
  "The night before everything changes",
  "A dance floor heartbreak",
  "A festival ferris wheel kiss",
  "The comedown after the lights",
  "A summer night you never fully remember",
  "A dangerous amount of confidence",
  "A city that does not sleep",
  "Glitter, sweat, and bad ideas",
  "A toast to making it this far",
  "Walking a runway like revenge",
  "Red carpet under flashbulbs",
  "Designer sunglasses and emotional distance",
  "A private jet after heartbreak",
  "Luxury hotel loneliness",
  "A fashion campaign shoot at midnight",
  "A superstar in dark glasses",
  "Champagne in the limousine",
  "Wearing diamonds and feeling nothing",
  "Designer heels in a dangerous city",
  "A celebrity exiting through the back door",
  "A paparazzi chase in Paris",
  "Front row at fashion week",
  "A magazine cover comeback",
  "Rich girl with a secret",
  "Quiet luxury but make it ruthless",
  "Silk sheets and trust issues",
  "Black-tie gala tension",
  "A mansion with too many empty rooms",
  "Expensive clothes on a cheap heart",
  "All-black outfit airport confidence",
  "Flash photography and fake intimacy",
  "A hotel elevator with history",
  "A brand-new chain after a long struggle",
  "Fashion as armor",
  "Power dressing after heartbreak",
  "A world tour wardrobe reveal",
  "A gold watch and no peace of mind",
  "Champagne towers and old wounds",
  "Looking expensive after surviving poverty",
  "Velvet ropes and hidden sadness",
  "A penthouse after the party",
  "Style becoming identity",
  "Luxury used as self-defense",
  "A couture look with teeth",
  "An icon stepping out of the car",
  "Flashbulbs in the rain",
  "A glossy magazine life with messy feelings",
  "Diamonds under nightclub lights",
  "Wearing confidence like a custom suit",
  "A runway walk after betrayal",
  "Pop-star fashion week energy",
  "A luxury vacation with unresolved tension",
  "Black car service at midnight",
  "Old money elegance and cold silence",
  "New money celebration",
  "A glam room before the performance",
  "Red lipstick before the revenge scene",
  "Fame, fashion, and emotional distance",
  "Looking untouchable on purpose",
  "A city that prices out its artists",
  "Working hard and still being broke",
  "The algorithm deciding your worth",
  "A generation tired before 30",
  "Living online and feeling unseen",
  "Protest signs in the rain",
  "The gap between rich and real",
  "Hustle culture eating people alive",
  "Politics at the family dinner table",
  "A quiet revolution starting",
  "Burnout as a shared language",
  "Everyone performing wellness",
  "The loneliness of modern cities",
  "News cycles moving too fast to grieve",
  "Consumerism as religion",
  "A job market with no mercy",
  "Being watched by cameras everywhere",
  "The internet turning pain into content",
  "Rent rising while hope falls",
  "The cost of existing",
  "A world full of branding and emptiness",
  "A generation raised by screens",
  "The pressure to monetize everything",
  "Chasing status in a collapsing system",
  "A protest march at sunset",
  "The death of privacy",
  "Working yourself empty for approval",
  "Manufactured outrage every day",
  "Communities built online because real life failed",
  "The sound of resistance growing",
  "Wealth looking clean and violence staying hidden",
  "A future sold as progress",
  "Climate anxiety in the summer heat",
  "Watching institutions fail in real time",
  "The quiet rage of workers",
  "A strike line before dawn",
  "Living through a cultural shift",
  "Art surviving a broken economy",
  "A city pushing people out",
  "The lie of endless productivity",
  "Watching a system crack",
  "Young people inheriting chaos",
  "Hope as a political act",
  "Noise, headlines, and emotional fatigue",
  "Identity under public pressure",
  "A movement bigger than one person",
  "The market swallowing meaning",
  "The human cost of convenience",
  "A society built on burnout",
  "Trying to stay human in a machine world",
  "A dragon crossing the night sky",
  "A knight facing impossible odds",
  "Entering an enchanted forest",
  "A wizard opening a portal",
  "Discovering an ancient relic",
  "A hidden kingdom in the mountains",
  "A prophecy awakening",
  "A magical duel under moonlight",
  "A traveler stepping between worlds",
  "A starship leaving Earth forever",
  "An alien signal from deep space",
  "A city floating above the clouds",
  "A cosmic storm over distant planets",
  "A hero touching forbidden power",
  "A spaceship entering hyperspace",
  "A dragon guarding a forgotten temple",
  "A galaxy unfolding outside the window",
  "A dream realm made of light",
  "An ancient machine waking up",
  "A final battle at the gates",
  "A sword pulled from stone",
  "A glowing artifact in the dark",
  "An astronaut drifting beyond radio contact",
  "A hidden portal in the sky",
  "A mystical forest with no exit",
  "A star map pointing somewhere impossible",
  "A chosen one refusing destiny",
  "A moonlit castle on the hill",
  "A rogue AI learning to feel",
  "A dimension folding in on itself",
  "A dragon sleeping under a city",
  "An alien city beneath an ocean",
  "A wizard tower during a thunderstorm",
  "A hero returning after exile",
  "A creature made of stars",
  "A kingdom under eclipse",
  "A spaceship lost in a nebula",
  "A temple opening after centuries",
  "A portal humming in an empty field",
  "A legend becoming real",
  "Feels like prom night in a disaster movie",
  "Feels like a cartoon villain at fashion week",
  "Feels like a breakup song for people who hate crying",
  "Feels like winning and still feeling empty",
  "Feels like a city-pop anime ending after heartbreak",
  "Feels like a luxury hotel during the apocalypse",
  "Feels like a black-and-white movie in a neon city",
  "Feels like a love song written by a liar",
  "Feels like the cool girl finally losing composure",
  "Feels like a summer hit with a dark secret",
  "Feels like fame at the exact wrong time",
  "Feels like the internet falling in love with you overnight",
  "Feels like a train ride between two versions of yourself",
  "Feels like the last good night before everything changes",
  "Feels like a pop anthem for emotionally unavailable people",
  "Feels like dancing through personal collapse",
  "Feels like a sports anime comeback but for your real life",
  "Feels like revenge in designer shoes",
  "Feels like your ex seeing you thrive in public",
  "Feels like a sad song pretending to be a party song",
  "Feels like a confessional in a club bathroom",
  "Feels like a road movie with no destination",
  "Feels like main-character energy with consequences",
  "Feels like a dream sequence inside a panic attack",
  "Feels like a mall in 2003 and a broken heart in 2026",
  "Feels like internet fame and no privacy",
  "Feels like the villain had a point",
  "Feels like a perfect night with terrible timing",
  "Feels like city lights hiding real sadness",
  "Feels like old friends in a new world",
  "Feels like a choir in a nightclub",
  "Feels like a love letter written on a deadline",
  "Feels like confidence built out of damage",
  "Feels like a vintage romance with modern trust issues",
  "Feels like a final boss fight against your old self",
  "Feels like a dancefloor confession",
  "Feels like soft launch, hard crash",
  "Feels like a movie montage for finally leaving",
  "Feels like a red carpet panic attack",
  "Feels like a hit single about emotional bankruptcy",
  "Feels like a rooftop kiss and an impending disaster",
  "Feels like nostalgia with sharp edges",
  "Feels like being adored for the wrong reasons",
  "Feels like an expensive goodbye",
  "Feels like surviving long enough to become iconic",
  "Feels like a fashion campaign for heartbreak",
  "Feels like healing in public",
  "Feels like the morning after a life-changing decision",
  "Feels like a late-night text you should not answer",
  "Feels like becoming your own myth",
  "Feels like a pop star in a noir film",
  "Feels like running away without moving",
  "Feels like making peace in high definition",
  "Feels like a standing ovation after total collapse",
  "Feels like a city remembering your name",
  "Feels like a goodbye dressed as a comeback",
  "Feels like growing up in one chorus",
  "Feels like a movie ending where nobody fully wins",
  "Feels like your life finally sounding like you meant it",
  "Feels like the start of the era you were born for",
];
